# Generated by Django 5.0.14 on 2026-05-09 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('final_proposal', 'Proposta Final'), ('contract', 'Contrato'), ('handover', 'Handover Package'), ('kickoff', 'Kickoff Pack'), ('checklist', 'Checklist de Arranque'), ('other', 'Outro')], default='other', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('attached', 'Anexado'), ('approved', 'Aprovado')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/artifacts/%Y/%m/')),
                ('external_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_artifacts_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='projects.project')),
            ],
            options={
                'ordering': ['artifact_type', 'title'],
            },
        ),
    ]
