# Generated by Django 5.0.14 on 2026-05-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectartifact',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='projects.projectphase'),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
