[pytest]
DJANGO_SETTINGS_MODULE = config.settings.local
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = --import-mode=importlib --cov=apps --cov-report=term-missing --cov-report=html:htmlcov -v
