# Generated by Django 5.0.14 on 2026-04-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("client", models.CharField(max_length=200)),
                (
                    "client_logo",
                    models.ImageField(blank=True, null=True, upload_to="client_logos/"),
                ),
                ("sector", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("deadline", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Novo"),
                            ("analyzing", "Em Analise"),
                            ("go", "Go"),
                            ("no_go", "No-Go"),
                            ("proposal_draft", "Proposta em Rascunho"),
                            ("proposal_review", "Proposta em Revisao"),
                            ("submitted", "Submetida"),
                            ("won", "Ganha"),
                            ("lost", "Nao Aprovada"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "evaluation_criteria",
                    models.CharField(
                        choices=[
                            ("qcbs", "QCBS (Qualidade e Custo)"),
                            ("cqs", "CQS (Qualidade apenas)"),
                            ("lcs", "LCS (Custo mais baixo)"),
                            ("fbs", "FBS (Baseado em Fixo)"),
                        ],
                        default="qcbs",
                        max_length=10,
                    ),
                ),
                ("technical_weight", models.PositiveIntegerField(default=70)),
                ("financial_weight", models.PositiveIntegerField(default=30)),
                (
                    "tor_document",
                    models.FileField(blank=True, null=True, upload_to="tor_documents/"),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("url_source", models.URLField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "ai_analysis_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "A processar"),
                            ("completed", "Completo"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Opportunities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("functional", "Funcionais"),
                            ("technical", "Tecnicos"),
                            ("institutional", "Institucionais"),
                            ("financial", "Financeiros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("mandatory", "Obrigatorio"),
                            ("preferred", "Preferencial"),
                            ("optional", "Opcional"),
                        ],
                        default="mandatory",
                        max_length=20,
                    ),
                ),
                ("is_covered", models.BooleanField(default=False)),
                ("covered_in", models.CharField(blank=True, max_length=200)),
                ("extracted_by_ai", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Baixo"), ("medium", "Medio"), ("high", "Alto")],
                        max_length=10,
                    ),
                ),
                ("mitigation", models.TextField(blank=True)),
                ("identified_by_ai", models.BooleanField(default=False)),
            ],
        ),
    ]
