# Generated by Django 5.0.14 on 2026-04-20 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opportunities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_opportunities", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risks",
                to="opportunities.opportunity",
            ),
        ),
    ]
