# Generated by Django 5.0.14 on 2026-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_opportunityscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='sector',
            field=models.CharField(choices=[('education', 'Educação'), ('health', 'Saúde'), ('social_protection', 'Protecção Social'), ('gender', 'Género e Igualdade'), ('water_sanitation', 'Água e Saneamento'), ('food_security', 'Segurança Alimentar'), ('nutrition', 'Nutrição'), ('housing', 'Habitação'), ('agriculture', 'Agricultura'), ('livestock', 'Pecuária'), ('fisheries', 'Pescas'), ('rural_development', 'Desenvolvimento Rural'), ('energy', 'Energia'), ('renewable_energy', 'Energias Renováveis'), ('mining', 'Mineração'), ('tourism', 'Turismo'), ('commerce', 'Comércio'), ('industry', 'Indústria'), ('financial_services', 'Serviços Financeiros'), ('private_sector', 'Sector Privado'), ('infrastructure', 'Infraestruturas'), ('transport', 'Transportes'), ('roads', 'Estradas'), ('ports', 'Portos'), ('aviation', 'Aviação Civil'), ('urban_development', 'Desenvolvimento Urbano'), ('construction', 'Construção Civil'), ('digital_infrastructure', 'Infraestruturas Digitais'), ('governance', 'Governação'), ('public_administration', 'Administração Pública'), ('decentralization', 'Descentralização'), ('justice', 'Justiça'), ('human_rights', 'Direitos Humanos'), ('civil_society', 'Sociedade Civil'), ('elections', 'Processos Eleitorais'), ('anti_corruption', 'Anti-Corrupção'), ('environment', 'Ambiente'), ('climate_change', 'Alterações Climáticas'), ('biodiversity', 'Biodiversidade'), ('waste_management', 'Gestão de Resíduos'), ('sustainable_development', 'Desenvolvimento Sustentável'), ('ict', 'ICT / Tecnologias de Informação'), ('digital_transformation', 'Transformação Digital'), ('cybersecurity', 'Cibersegurança'), ('e_government', 'Governo Electrónico'), ('data_science', 'Ciência de Dados'), ('monitoring_evaluation', 'Monitoria e Avaliação'), ('research', 'Investigação'), ('capacity_building', 'Capacitação Institucional'), ('procurement', 'Contratação Pública'), ('supply_chain', 'Cadeia de Abastecimento'), ('emergency_response', 'Resposta a Emergências'), ('humanitarian_aid', 'Ajuda Humanitária'), ('migration', 'Migração'), ('youth_employment', 'Emprego Juvenil'), ('cultural_heritage', 'Património Cultural'), ('statistics', 'Estatística'), ('telecom', 'Telecomunicações'), ('maritime', 'Economia Azul / Marítimo')], max_length=100),
        ),
    ]
