# Generated by Django 5.0.14 on 2026-05-18 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_alter_opportunity_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default firm profile', max_length=200)),
                ('target_sectors', models.JSONField(blank=True, default=list)),
                ('geographies', models.JSONField(blank=True, default=list)),
                ('scoring_weights_override', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_firm_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('view_type', models.CharField(choices=[('opportunities', 'Opportunities'), ('scraping', 'Scraping'), ('proposals', 'Proposals')], default='opportunities', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['view_type', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='savedfilter',
            constraint=models.UniqueConstraint(fields=('owner', 'view_type', 'name'), name='unique_saved_filter_per_owner_view_name'),
        ),
    ]
