# Generated by Django 5.0.14 on 2026-05-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_firmprofile_savedfilter_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm_profiles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='tenants.tenant'),
        ),
    ]
