# Generated by Django 5.0.14 on 2026-04-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('external_url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Nova'), ('imported', 'Importada'), ('ignored', 'Ignorada'), ('expired', 'Expirada')], default='new', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_alert', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_extracted_requirements', models.JSONField(blank=True, default=list)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_opportunity', 'Nova Oportunidade'), ('deadline_approaching', 'Prazo Proximo'), ('status_change', 'Alteracao de Estado'), ('value_threshold', 'Valor Acima do Limite')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'A executar'), ('completed', 'Completo'), ('failed', 'Falhou'), ('scheduled', 'Agendado')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('items_new', models.PositiveIntegerField(default=0)),
                ('items_imported', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('executed_by', models.CharField(choices=[('scheduler', 'Agendador'), ('manual', 'Manual'), ('user', 'Utilizador')], default='scheduler', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('logo', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('portal', 'Portal'), ('rss', 'RSS Feed'), ('api', 'API'), ('job_board', 'Job Board')], default='portal', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('error', 'Erro'), ('disabled', 'Desativado')], default='active', max_length=20)),
                ('scrape_frequency', models.CharField(choices=[('hourly', 'Por Hora'), ('daily', 'Diario'), ('weekly', 'Semanal')], default='daily', max_length=20)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('next_scrape_at', models.DateTimeField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('scraper_class', models.CharField(default='BaseScraper', max_length=100)),
                ('scraper_config', models.JSONField(blank=True, default=dict)),
                ('new_opportunities_count', models.PositiveIntegerField(default=0)),
                ('total_opportunities_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.PositiveIntegerField(default=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
