# Generated by Django 5.0.14 on 2026-04-30 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0002_initial'),
        ('scraping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedopportunity',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='imported_opportunity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_source', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='scrapingalert',
            name='scraped_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.scrapedopportunity'),
        ),
        migrations.AddField(
            model_name='scrapingalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scraping.scrapingsource'),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_opportunities', to='scraping.scrapingsource'),
        ),
        migrations.AlterUniqueTogether(
            name='scrapedopportunity',
            unique_together={('source', 'external_id')},
        ),
    ]
