# Generated by Django 5.0.14 on 2026-05-06 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_initial'),
        ('scraping', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedopportunity',
            name='cv_eligible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='data_quality_score',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='deadline_timezone',
            field=models.CharField(default='Atlantic/Cape_Verde', max_length=50),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='deadline_validation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='eligibility_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='geographic_scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='ingestion_batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='raw_content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='sector_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='transformation_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='batch_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='items_duplicate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='items_rejected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapedopportunity',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapedopportunity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scrapedopportunity',
            name='status',
            field=models.CharField(choices=[('new', 'Nova'), ('imported', 'Importada'), ('ignored', 'Ignorada'), ('expired', 'Expirada'), ('rejected', 'Rejeitada')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scrapedopportunity',
            index=models.Index(fields=['status', 'scraped_at'], name='scraping_sc_status_257b57_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedopportunity',
            index=models.Index(fields=['cv_eligible', 'deadline'], name='scraping_sc_cv_elig_7a0feb_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedopportunity',
            index=models.Index(fields=['ingestion_batch_id'], name='scraping_sc_ingesti_37ae00_idx'),
        ),
    ]
