from django.db import migrations

DEFAULT_SOURCES = [
    {
        'name': 'UGPE - Concursos Cabo Verde',
        'organization': 'UGPE',
        'url': 'https://ugpe.gov.cv/concursos',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'UGPEScraper',
        'scraper_config': {
            'url': 'https://ugpe.gov.cv/concursos',
            'item_selectors': [
                'table.concursos-table tbody tr',
                'div.concurso-item',
                'div.opportunity-item',
            ],
        },
        'filters': {
            'countries': ['CPV'],
            'keywords': ['consultoria', 'consultor', 'consultant'],
        },
    },
    {
        'name': 'ECREEE - Procurement Notices',
        'organization': 'ECREEE / CEDEAO',
        'url': 'https://www.ecreee.org/category/procurement-notices/',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'ECREEEScraper',
        'scraper_config': {
            'url': 'https://www.ecreee.org/category/procurement-notices/',
            'item_selectors': [
                'article.post',
                'div.post',
                'article.type-post',
            ],
        },
        'filters': {
            'countries': ['CPV', 'GHA', 'SEN', 'NGA'],
            'keywords': ['consultancy', 'consultant', 'expert', 'advisor'],
        },
    },
    {
        'name': 'World Bank - Operational Consulting',
        'organization': 'World Bank Group',
        'url': 'https://www.worldbank.org/en/about/corporate-procurement/business-opportunities/operational-consulting-opportunities',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'WorldBankScraper',
        'scraper_config': {
            'url': 'https://www.worldbank.org/en/about/corporate-procurement/business-opportunities/operational-consulting-opportunities',
            'api_url': 'https://search.worldbank.org/api/v2/procurement',
            'fields': 'id,title,deadline,pdate,countryname,regionname,project_name,url,borrower,sector,docty',
            'filter_query': 'docty:Notice AND status:Active',
            'page_size': 50,
            'max_items': 200,
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'advisory', 'technical assistance'],
        },
    },
    {
        'name': 'AfDB - Consultant Vacancies',
        'organization': 'African Development Bank',
        'url': 'https://www.afdb.org/en/about-us/careers/current-vacancies/consultants',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'AfDBScraper',
        'scraper_config': {
            'url': 'https://www.afdb.org/en/about-us/careers/current-vacancies/consultants',
            'api_url': 'https://www.afdb.org/api/v1/node/procurement',
            'rss_url': 'https://www.afdb.org/en/projects-and-operations/procurement/rss',
            'page_size': 50,
            'page': 0,
            'status': 1,
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'expert'],
        },
    },
    {
        'name': 'UNDP - Job Opportunities',
        'organization': 'UNDP',
        'url': 'https://jobs.undp.org/cj_view_jobs.cfm',
        'source_type': 'job_board',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'UNDPScraper',
        'scraper_config': {
            'url': 'https://jobs.undp.org/cj_view_jobs.cfm',
            'api_url': 'https://www.ungm.org/Public/Notice',
            'rss_url': 'https://procurement-notices.undp.org/feed.cfm?po_filter=all',
            'notice_type': 0,
            'page_size': 50,
            'max_items': 200,
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'international consultant'],
        },
    },
    {
        'name': 'LuxDev - Call for Tenders',
        'organization': 'LuxDev',
        'url': 'https://luxdev.lu/en/tenders/call-tenders',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'LuxDevScraper',
        'scraper_config': {
            'urls': [
                'https://luxdev.lu/en/tenders/call-tenders',
                'https://luxdev.lu/en/tenders/calls-proposals',
            ],
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'ACP'],
            'keywords': ['consultant', 'tender', 'proposal', 'expertise'],
        },
    },
    {
        'name': 'FAO - Cabo Verde Procurement',
        'organization': 'FAO',
        'url': 'https://www.fao.org/cabo-verde/fao-au-cabo-verde/procurement/en/',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.fao.org/cabo-verde/fao-au-cabo-verde/procurement/en/',
            'item_selectors': ['div.item', 'article', 'tr', 'li'],
            'title_selector': 'h3, h4, a, strong',
            'link_selector': 'a[href]',
            'description_selector': 'p, .description',
            'deadline_selector': '.deadline, .date',
            'organization': 'FAO',
            'client': 'FAO Cabo Verde',
            'country': 'Cabo Verde',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV'],
            'keywords': ['consultant', 'consultancy', 'procurement'],
        },
    },
    {
        'name': 'Instituto Camões - Oportunidades',
        'organization': 'Instituto Camões, I.P.',
        'url': 'https://www.instituto-camoes.pt/activity/oportunidades',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.instituto-camoes.pt/activity/oportunidades',
            'item_selectors': ['article', 'div.item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, .summary',
            'organization': 'Instituto Camões',
            'client': 'Instituto Camões, I.P.',
            'country': 'PALOP',
            'language': 'pt',
        },
        'filters': {
            'countries': ['CPV', 'AO', 'MZ', 'GW', 'ST', 'PT'],
            'keywords': ['consultor', 'consultoria', 'especialista', 'perito'],
        },
    },
    {
        'name': 'AECID - Cooperação Cabo Verde',
        'organization': 'AECID',
        'url': 'https://www.aecid.es',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.aecid.es',
            'item_selectors': ['article', 'div.item', 'tr'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'AECID',
            'client': 'Agência Espanhola de Cooperação',
            'country': 'Cabo Verde',
            'language': 'es',
        },
        'filters': {
            'countries': ['CPV'],
            'keywords': ['consultor', 'consultoria', 'cooperación'],
        },
    },
    {
        'name': 'ECOWAS / CEDEAO - Procurement',
        'organization': 'ECOWAS',
        'url': 'https://www.ecowas.int',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.ecowas.int',
            'item_selectors': ['article', 'div.item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'ECOWAS / CEDEAO',
            'client': 'ECOWAS',
            'country': 'Regional',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'West Africa'],
            'keywords': ['consultant', 'consultancy', 'procurement'],
        },
    },
    {
        'name': 'dgMarket - Global Tenders',
        'organization': 'dgMarket',
        'url': 'https://www.dgmarket.com',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.dgmarket.com',
            'item_selectors': ['div.tender-item', 'tr', 'article'],
            'title_selector': 'h3, a.tender-title',
            'link_selector': 'a[href]',
            'description_selector': '.description, p',
            'organization': 'dgMarket',
            'client': 'Various',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'advisory'],
        },
    },
    {
        'name': 'EU Funding & Tenders Portal',
        'organization': 'European Commission',
        'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search',
            'item_selectors': ['div.topic-item', 'tr', 'article', 'li'],
            'title_selector': 'h3, h4, a, strong',
            'link_selector': 'a[href]',
            'description_selector': 'p, .description',
            'deadline_selector': '.deadline, .date, .end-date',
            'organization': 'European Commission',
            'client': 'EU',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV'],
            'keywords': ['consultant', 'consultancy', 'expert', 'technical assistance'],
            'programmes': [
                'NDICI', 'Global Gateway', 'ARISE', 'EU-AITF',
                'Intra-Africa Mobility', 'AU-EU Youth Lab', 'Digital Innovation',
            ],
        },
    },
    {
        'name': 'DG INTPA - EU International Partnerships',
        'organization': 'European Commission - DG INTPA',
        'url': 'https://international-partnerships.ec.europa.eu',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://international-partnerships.ec.europa.eu',
            'item_selectors': ['article', 'div.item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'European Commission',
            'client': 'DG INTPA',
            'country': 'Africa',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV'],
            'keywords': ['grant', 'funding', 'consultancy', 'expert'],
            'sectors': ['green energy', 'health', 'digital', 'education', 'youth'],
        },
    },
    {
        'name': 'TED - Tenders Electronic Daily',
        'organization': 'Publications Office of the EU',
        'url': 'https://ted.europa.eu',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://ted.europa.eu',
            'item_selectors': ['div.notice', 'tr', 'article'],
            'title_selector': 'h3, a.notice-title',
            'link_selector': 'a[href]',
            'description_selector': '.description, p',
            'organization': 'EU',
            'client': 'Various EU Institutions',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'technical assistance'],
        },
    },
    {
        'name': 'EIB - European Investment Bank',
        'organization': 'EIB',
        'url': 'https://www.eib.org/en/about/procurement/calls/index.htm',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.eib.org/en/about/procurement/calls/index.htm',
            'item_selectors': [
                'table.standard-table tbody tr',
                'div.eib-component__tender-item',
                'div.tender-item',
                'article.tender',
                'li.tender',
                'tr',
            ],
            'title_selector': 'td:nth-child(2) a, td:first-child a, h3 a, h4 a, a',
            'link_selector': 'a[href]',
            'description_selector': 'td:nth-child(2), p, .description',
            'deadline_selector': 'td:last-child, .deadline, .closing-date',
            'reference_selector': 'td:first-child, .reference',
            'organization': 'EIB',
            'client': 'European Investment Bank',
            'country': 'Africa / International',
            'language': 'en',
            'reject_title_patterns': [
                r'^The EIB (and|at|in|Group)\b',
                r'^EIB (Group|Board|Annual|Report|Press|Strategy)',
                r'\b(annual report|press release|speech|interview|publication)\b',
            ],
        },
        'filters': {
            'countries': ['Africa', 'CPV'],
            'keywords': ['consultant', 'consulting', 'advisory', 'tender', 'procurement',
                         'infrastructure', 'energy', 'expression of interest'],
        },
    },
    {
        'name': 'Devex - Development Jobs & Tenders',
        'organization': 'Devex',
        'url': 'https://www.devex.com',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.devex.com',
            'item_selectors': ['div.job-item', 'article', 'tr'],
            'title_selector': 'h3, a.job-title',
            'link_selector': 'a[href]',
            'description_selector': 'p, .description',
            'organization': 'Devex',
            'client': 'Various',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'advisor'],
        },
    },
    {
        'name': 'AFD - Procurement',
        'organization': 'Agence Francaise de Developpement',
        'url': 'https://www.afd.fr/en/procurement',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.afd.fr/en/procurement',
            'item_selectors': ['article', 'div.item', 'tr', 'li'],
            'title_selector': 'h2, h3, a, strong',
            'link_selector': 'a[href]',
            'description_selector': 'p, .description',
            'deadline_selector': '.deadline, .date',
            'organization': 'AFD',
            'client': 'Agence Francaise de Developpement',
            'country': 'Africa',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'appel d offres', 'technical assistance'],
            'sectors': ['blue economy', 'fisheries', 'infrastructure', 'energy'],
        },
    },
    {
        'name': 'Fundacao Calouste Gulbenkian - Financiamentos',
        'organization': 'Fundacao Calouste Gulbenkian',
        'url': 'https://gulbenkian.pt/pt/ajuda/financiamentos/',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://gulbenkian.pt/pt/ajuda/financiamentos/',
            'item_selectors': ['article', 'div.item', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, .summary',
            'organization': 'Fundacao Calouste Gulbenkian',
            'client': 'Fundacao Calouste Gulbenkian',
            'country': 'Portugal / PALOP',
            'language': 'pt',
        },
        'filters': {
            'countries': ['CPV', 'PT', 'PALOP'],
            'keywords': ['financiamento', 'bolsa', 'consultoria', 'desenvolvimento'],
        },
    },
    {
        'name': 'UNGM - United Nations Global Marketplace',
        'organization': 'United Nations',
        'url': 'https://www.ungm.org/Public/Notice',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.ungm.org/Public/Notice',
            'item_selectors': ['tr', 'div.notice', 'article'],
            'title_selector': 'a, h3, h4',
            'link_selector': 'a[href]',
            'description_selector': 'p, td',
            'deadline_selector': '.deadline, td',
            'organization': 'United Nations',
            'client': 'UN Agencies',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'technical assistance', 'evaluation'],
        },
    },
    {
        'name': 'UNOPS - Careers Africa',
        'organization': 'UNOPS',
        'url': 'https://www.unops.org/careers',
        'source_type': 'job_board',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.unops.org/careers',
            'item_selectors': ['article', 'div.job-item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'UNOPS',
            'client': 'UNOPS',
            'country': 'Africa',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'specialist', 'advisor', 'infrastructure'],
        },
    },
    {
        'name': 'UNICEF - Careers and Consultancies',
        'organization': 'UNICEF',
        'url': 'https://www.unicef.org/careers',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.unicef.org/careers',
            'item_selectors': ['article', 'div.job-item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'UNICEF',
            'client': 'UNICEF',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'evaluation', 'specialist'],
            'sectors': ['health', 'education', 'child protection', 'social policy'],
        },
    },
    {
        'name': 'World Bank - Projects Cabo Verde',
        'organization': 'World Bank Group',
        'url': 'https://projects.worldbank.org',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'WorldBankScraper',
        'scraper_config': {
            'url': 'https://projects.worldbank.org',
            'api_url': 'https://search.worldbank.org/api/v2/projects',
            'format': 'json',
            'countrycode_exact': 'CV',
            'page_size': 50,
            'max_items': 100,
        },
        'filters': {
            'countries': ['CPV'],
            'keywords': ['consultant', 'consulting services', 'technical assistance', 'project'],
            'sectors': ['digital', 'tourism', 'health', 'blue economy', 'governance'],
        },
    },
    {
        'name': 'Development Business - Tenders',
        'organization': 'Development Business',
        'url': 'https://developmentbusiness.un.org',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://developmentbusiness.un.org',
            'item_selectors': ['article', 'div.notice', 'tr'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, .description',
            'deadline_selector': '.deadline, .date',
            'organization': 'Development Business',
            'client': 'Multilateral Development Banks',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'expression of interest', 'request for proposals'],
        },
    },
    {
        'name': 'Impactpool - International Development Jobs',
        'organization': 'Impactpool',
        'url': 'https://www.impactpool.org',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.impactpool.org',
            'item_selectors': ['article', 'div.job-item', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'Impactpool',
            'client': 'Various',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'advisor', 'expert'],
        },
    },
    {
        'name': 'UNjobnet - UN Jobs',
        'organization': 'UNjobnet',
        'url': 'https://www.unjobnet.org',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.unjobnet.org',
            'item_selectors': ['article', 'div.job-item', 'tr'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'UNjobnet',
            'client': 'UN Agencies',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'AFRITAC', 'technical assistance'],
        },
    },
    {
        'name': 'UN Talent - Consulting Opportunities',
        'organization': 'UN Talent',
        'url': 'https://untalent.org',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://untalent.org',
            'item_selectors': ['article', 'div.job-item', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'UN Talent',
            'client': 'UN Agencies',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'volunteer', 'specialist'],
        },
    },
    {
        'name': 'ReliefWeb - Jobs',
        'organization': 'ReliefWeb',
        'url': 'https://reliefweb.int/jobs',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://reliefweb.int/jobs',
            'item_selectors': ['article', 'div.rw-river-article', 'li'],
            'title_selector': 'h3, h2, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'ReliefWeb',
            'client': 'Humanitarian Organizations',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'advisor', 'evaluation'],
            'sectors': ['humanitarian', 'health', 'resilience', 'development'],
        },
    },
    {
        'name': 'CILSS - Sahel Opportunities',
        'organization': 'CILSS',
        'url': 'https://www.cilss.int',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.cilss.int',
            'item_selectors': ['article', 'div.item', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'CILSS',
            'client': 'CILSS',
            'country': 'Sahel / West Africa',
            'language': 'fr',
        },
        'filters': {
            'countries': ['CPV', 'West Africa', 'Sahel'],
            'keywords': ['consultant', 'consultance', 'expert', 'securite alimentaire'],
            'sectors': ['food security', 'environment', 'climate resilience'],
        },
    },
    {
        'name': 'BOAD - Procurement',
        'organization': 'BOAD',
        'url': 'https://www.boad.org',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.boad.org',
            'item_selectors': ['article', 'div.item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'BOAD',
            'client': 'West African Development Bank',
            'country': 'West Africa',
            'language': 'fr',
        },
        'filters': {
            'countries': ['CPV', 'West Africa'],
            'keywords': ['consultant', 'consultance', 'appel d offres', 'expert'],
            'sectors': ['infrastructure', 'energy', 'agriculture', 'governance'],
        },
    },
]


def seed_default_sources(apps, schema_editor):
    ScrapingSource = apps.get_model('scraping', 'ScrapingSource')
    for src_data in DEFAULT_SOURCES:
        ScrapingSource.objects.update_or_create(
            name=src_data['name'],
            defaults={
                'organization': src_data['organization'],
                'url': src_data['url'],
                'source_type': src_data['source_type'],
                'status': src_data['status'],
                'scrape_frequency': src_data['scrape_frequency'],
                'scraper_class': src_data['scraper_class'],
                'scraper_config': src_data.get('scraper_config', {}),
                'filters': src_data.get('filters', {}),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_scrapedopportunity_cv_eligible_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_sources, migrations.RunPython.noop),
    ]
