# Generated by Django 5.0.14 on 2026-05-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_seed_default_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedopportunity',
            name='deep_content_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='deep_content_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='deep_content_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scrapedopportunity',
            name='deep_content_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
