# Generated by Django 5.0.14 on 2026-05-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0012_add_requested_procurement_sources'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedopportunity',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_opportunities', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='scrapingalert',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_alerts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_sources', to='tenants.tenant'),
        ),
    ]
