# Generated by Django 5.0.14 on 2026-04-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AISuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("expand", "Expandir"),
                            ("summarize", "Resumir"),
                            ("tone_formal", "Ajustar Tom"),
                            ("translate_en", "Traduzir EN"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("generated_content", models.TextField(blank=True)),
                ("applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("in_review", "Em Revisao"),
                            ("qc_check", "QC em Curso"),
                            ("approved", "Aprovada"),
                            ("submitted", "Submetida"),
                            ("won", "Ganha"),
                            ("lost", "Perdida"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "auto_save_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("saving", "A guardar"),
                            ("saved", "Guardado"),
                            ("error", "Erro"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("last_saved_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposalSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("cover", "Capa"),
                            ("executive_summary", "Resumo Executivo"),
                            ("methodology", "Metodologia"),
                            ("team", "Equipa Tecnica"),
                            ("workplan", "Plano de Trabalho"),
                            ("budget", "Orcamento"),
                            ("annexes", "Anexos"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_complete", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProposalTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                ("hours", models.PositiveIntegerField(default=0)),
                ("hourly_rate", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("cv_attached", models.BooleanField(default=False)),
                ("cv_document", models.FileField(blank=True, null=True, upload_to="cv_documents/")),
            ],
        ),
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personnel", "Pessoal"),
                            ("travel", "Viagens"),
                            ("equipment", "Equipamentos"),
                            ("materials", "Materiais"),
                            ("overhead", "Overhead"),
                            ("other", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="proposals.budget",
                    ),
                ),
            ],
        ),
    ]
