# Generated by Django 5.0.14 on 2026-04-20 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opportunities", "0002_initial"),
        ("proposals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="proposal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget",
                to="proposals.proposal",
            ),
        ),
        migrations.AddField(
            model_name="proposalsection",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="proposals.proposal",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="proposals.proposalsection",
            ),
        ),
        migrations.AddField(
            model_name="aisuggestion",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_suggestions",
                to="proposals.proposalsection",
            ),
        ),
        migrations.AddField(
            model_name="proposalteammember",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="proposals.proposal"
            ),
        ),
        migrations.AddField(
            model_name="proposalteammember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="team_members",
            field=models.ManyToManyField(
                related_name="proposals",
                through="proposals.ProposalTeamMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
