# Generated by Django 5.0.14 on 2026-04-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="client_logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo do cliente",
                null=True,
                upload_to="proposals/logos/client/",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="consortium_members",
            field=models.JSONField(
                blank=True, default=list, help_text="Lista de membros do consórcio (se aplicável)"
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="proponent_logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo da empresa proponente ou consórcio",
                null=True,
                upload_to="proposals/logos/proponent/",
            ),
        ),
    ]
