# Generated by Django 5.0.14 on 2026-05-18 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_proposalevent_artifact_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PursuitGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_type', models.CharField(choices=[('strategic_fit', 'Strategic fit'), ('commercial_viability', 'Commercial viability'), ('delivery_capacity', 'Delivery capacity'), ('partner_approval', 'Partner approval')], max_length=40)),
                ('required_role', models.CharField(choices=[('consultant', 'Consultant'), ('manager', 'Manager'), ('admin', 'Partner/Admin')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pursuit_gates', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pursuit_gates', to='proposals.proposal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waived', 'Waived')], max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pursuit_gate_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_audit_logs', to='proposals.proposal')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='proposals.pursuitgate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pursuitgate',
            constraint=models.UniqueConstraint(fields=('proposal', 'gate_type'), name='unique_pursuit_gate_per_proposal_type'),
        ),
    ]
