# Generated by Codex on 2026-05-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_pursuitgate_gateauditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalPostMortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled'), ('no_decision', 'No decision')], max_length=20)),
                ('outcome_reason', models.TextField(blank=True)),
                ('client_feedback', models.TextField(blank=True)),
                ('lessons_learned', models.JSONField(blank=True, default=list)),
                ('scoring_adjustments', models.JSONField(blank=True, default=dict)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_post_mortems', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_mortem', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('executive_summary', 'Executive summary'), ('board_pack', 'Board pack'), ('pdf', 'PDF'), ('pptx', 'PPTX')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('executive_summary', models.TextField(blank=True)),
                ('output_metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to='proposals.proposal')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='proposalexportrequest',
            index=models.Index(fields=['proposal', 'status'], name='proposals_p_proposa_9e1c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalexportrequest',
            index=models.Index(fields=['export_type', 'created_at'], name='proposals_p_export_55ab97_idx'),
        ),
    ]
