# Generated by Django 5.0.14 on 2026-05-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_proposalpostmortem_proposalexportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalexportrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalexportrequest',
            name='execution_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposalexportrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalexportrequest',
            name='task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
