# Generated by Django 5.0.14 on 2026-05-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0004_seed_cv_templates"),
        ("proposals", "0012_export_request_execution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Update Django's migration state to remove the old unique_together.
        # SQLite may not expose it as a droppable named index, so we skip the
        # database operation here; the table rebuild triggered by AlterField
        # below will omit it automatically.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="proposalteammember",
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="proposalteammember",
            name="curriculum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposal_memberships",
                to="curriculum.curriculum",
            ),
        ),
        migrations.AddField(
            model_name="proposalteammember",
            name="suggested_profile",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Free-text profile description for suggested (non-user) slots.",
            ),
        ),
        migrations.AddField(
            model_name="proposalteammember",
            name="team_member_status",
            field=models.CharField(
                choices=[
                    ("suggested_profile", "Perfil Sugerido"),
                    ("consultant_in_negotiation", "Consultor em Negociacao"),
                    ("cv_pending", "CV Pendente"),
                    ("confirmed", "Confirmado"),
                ],
                default="cv_pending",
                max_length=30,
            ),
        ),
        # Making user nullable triggers a table rebuild in SQLite, which will
        # recreate the table without the old unique_together.
        migrations.AlterField(
            model_name="proposalteammember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Add the replacement partial unique constraint (only when user is set).
        migrations.AddConstraint(
            model_name="proposalteammember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("proposal", "user"),
                name="unique_proposal_user_when_set",
            ),
        ),
    ]
