# Generated by Django 5.0.14 on 2026-05-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_proposalteammember_cv_workflow'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='tenants.tenant'),
        ),
    ]
