# Generated by Django 5.0.14 on 2026-04-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QCCheckCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("compliance", "Conformidade com ToR"),
                            ("coherence", "Coerencia Narrativa"),
                            ("budget", "Orcamento"),
                            ("attachments", "Anexos"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("pass", "Aprovado"), ("warn", "Atencao"), ("fail", "Reprovado")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QCSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("replace", "Substituir"),
                            ("add", "Adicionar"),
                            ("remove", "Remover"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target_section", models.CharField(max_length=200)),
                ("applied", models.BooleanField(default=False)),
                ("ignored", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="QualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("overall_score", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "A executar"),
                            ("completed", "Completo"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("can_submit", models.BooleanField(default=False)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QCItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pass", "Aprovado"), ("warn", "Atencao"), ("fail", "Reprovado")],
                        max_length=10,
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quality_checks.qccheckcategory",
                    ),
                ),
            ],
        ),
    ]
