# Generated by Django 5.0.14 on 2026-04-20 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proposals", "0002_initial"),
        ("quality_checks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitycheck",
            name="executed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="qualitycheck",
            name="proposal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_check",
                to="proposals.proposal",
            ),
        ),
        migrations.AddField(
            model_name="qcsuggestion",
            name="quality_check",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions",
                to="quality_checks.qualitycheck",
            ),
        ),
        migrations.AddField(
            model_name="qccheckcategory",
            name="quality_check",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="quality_checks.qualitycheck",
            ),
        ),
    ]
