# Generated by Django 5.0.14 on 2026-04-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='curricula/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC')], max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Carregado'), ('processing', 'A processar'), ('analyzed', 'Analisado'), ('error', 'Erro')], default='uploaded', max_length=20)),
                ('analysis_score', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Curricula',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CVOpportunityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveIntegerField()),
                ('skills_match_score', models.PositiveIntegerField()),
                ('experience_match_score', models.PositiveIntegerField()),
                ('education_match_score', models.PositiveIntegerField()),
                ('language_match_score', models.PositiveIntegerField()),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('relevant_experiences', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='CVSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('missing_section', 'Secao em Falta'), ('format', 'Formato'), ('content', 'Conteudo'), ('keyword', 'Palavra-chave'), ('length', 'Extensao')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baixa')], max_length=10)),
                ('message', models.TextField()),
                ('context', models.CharField(blank=True, max_length=50)),
                ('auto_fixable', models.BooleanField(default=False)),
                ('fixed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(choices=[('world_bank', 'World Bank'), ('un', 'United Nations'), ('eu', 'European Union'), ('afdb', 'African Development Bank'), ('usaid', 'USAID'), ('giz', 'GIZ'), ('other', 'Other')], max_length=20)),
                ('organization_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_sections', models.JSONField(default=list)),
                ('format_rules', models.JSONField(default=list)),
                ('max_length_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('file_template', models.FileField(blank=True, null=True, upload_to='cv_templates/')),
                ('example_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.PositiveIntegerField()),
                ('missing_sections', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('adapted_content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
    ]
