# Generated by Django 5.0.14 on 2026-04-30 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cvopportunitymatch',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_matches', to='curriculum.curriculum'),
        ),
        migrations.AddField(
            model_name='cvopportunitymatch',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='cvsuggestion',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='curriculum.curriculum'),
        ),
        migrations.AddField(
            model_name='templatematch',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_matches', to='curriculum.curriculum'),
        ),
        migrations.AddField(
            model_name='templatematch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.cvtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='cvopportunitymatch',
            unique_together={('curriculum', 'opportunity')},
        ),
        migrations.AlterUniqueTogether(
            name='templatematch',
            unique_together={('curriculum', 'template')},
        ),
    ]
