# Generated by Django 5.0.14 on 2026-04-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatematch',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to='curriculum/generated/%Y/%m/'),
        ),
    ]
