# Generated by Django 5.0.14 on 2026-05-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_seed_cv_templates'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='tenants.tenant'),
        ),
    ]
