# Generated by Django 5.0.14 on 2026-05-19 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('proposal', 'Proposal'), ('proposal_section', 'Proposal section'), ('project', 'Project'), ('case', 'Case'), ('consultant_profile', 'Consultant profile'), ('cv', 'CV'), ('template', 'Template'), ('pricing', 'Pricing'), ('other', 'Other')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('source_app', models.CharField(blank=True, max_length=80)),
                ('source_model', models.CharField(blank=True, max_length=120)),
                ('source_id', models.CharField(blank=True, max_length=80, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['asset_type', 'status'], name='knowledge_k_asset_t_291f04_idx'), models.Index(fields=['country', 'sector'], name='knowledge_k_country_7da8c8_idx'), models.Index(fields=['source_app', 'source_model'], name='knowledge_k_source__f81653_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgeasset',
            constraint=models.UniqueConstraint(fields=('source_app', 'source_model', 'source_id'), name='unique_knowledge_asset_source'),
        ),
    ]
