REQUESTED_PROCUREMENT_SOURCES = [
    {
        'name': 'World Bank STEP - Procurement Portal',
        'organization': 'World Bank Group',
        'url': 'https://step.worldbank.org/',
        'source_type': 'api',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'WorldBankScraper',
        'scraper_config': {
            'url': 'https://step.worldbank.org/',
            'api_url': 'https://search.worldbank.org/api/v2/procurement',
            'fields': 'id,title,deadline,pdate,countryname,regionname,project_name,url,borrower,sector,docty,source',
            'filter_query': 'docty:Notice AND status:Active AND source:STEP',
            'page_size': 50,
            'max_items': 300,
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'West Africa', 'PALOP'],
            'keywords': ['consultant', 'consulting', 'technical assistance', 'expression of interest', 'request for proposal'],
        },
        'verify_ssl': True,
        'respect_robots_txt': True,
    },
    {
        'name': 'TradeMark Africa - Procurement',
        'organization': 'TradeMark Africa',
        'url': 'https://trademarkafrica.com/procurement/',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://trademarkafrica.com/procurement/',
            'item_selectors': ['article', 'div.card', 'div.tender', 'div.procurement', 'li', 'tr'],
            'title_selector': 'h2, h3, h4, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, td, div.description',
            'deadline_selector': 'time, td, .deadline, .closing-date',
            'organization': 'TradeMark Africa',
            'client': 'TradeMark Africa',
            'country': 'Africa',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'East Africa'],
            'keywords': ['procurement', 'consultancy', 'trade', 'market access', 'technical assistance'],
        },
    },
    {
        'name': 'ECOWAS - Procurement Portal',
        'organization': 'ECOWAS / CEDEAO',
        'url': 'https://www.ecowas.int/procurement/',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.ecowas.int/procurement/',
            'item_selectors': ['article', 'div.post', 'div.procurement', 'div.card', 'li'],
            'title_selector': 'h2, h3, h4, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.entry-content, div.excerpt',
            'deadline_selector': 'time, .deadline, .closing-date',
            'organization': 'ECOWAS',
            'client': 'ECOWAS / CEDEAO',
            'country': 'West Africa',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'West Africa', 'Africa'],
            'keywords': ['consultancy', 'consultant', 'procurement', 'tender', 'expression of interest'],
        },
    },
    {
        'name': 'UNIDO - Procurement Opportunities',
        'organization': 'UNIDO',
        'url': 'https://www.unido.org/get-involved/procurement/procurement-opportunities',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.unido.org/get-involved/procurement/procurement-opportunities',
            'item_selectors': ['article', 'div.view-row', 'div.card', 'li', 'tr'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, td, div.description',
            'deadline_selector': 'time, td, .deadline',
            'organization': 'UNIDO',
            'client': 'UNIDO',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'PALOP'],
            'keywords': ['procurement', 'consultancy', 'industrial development', 'technical assistance'],
        },
    },
    {
        'name': 'ECREEE - Procurements',
        'organization': 'ECREEE / CEDEAO',
        'url': 'https://www.ecreee.org/procurements',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'ECREEEScraper',
        'scraper_config': {
            'url': 'https://www.ecreee.org/procurements',
            'item_selectors': ['article', 'div.view-row', 'div.procurement', 'li'],
        },
        'filters': {
            'countries': ['CPV', 'West Africa', 'ECOWAS'],
            'keywords': ['renewable energy', 'energy efficiency', 'consultancy', 'procurement'],
        },
    },
    {
        'name': 'Green Climate Fund - Open Procurements',
        'organization': 'Green Climate Fund (GCF)',
        'url': 'https://www.greenclimate.fund/about/procurement#open-procurements',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.greenclimate.fund/about/procurement#open-procurements',
            'item_selectors': ['article', 'div.procurement', 'div.card', 'li', 'tr'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, td',
            'deadline_selector': 'time, td, .deadline',
            'organization': 'GCF',
            'client': 'Green Climate Fund',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'procurement', 'climate', 'adaptation', 'mitigation'],
        },
    },
    {
        'name': 'World Bank - Procurement Notices',
        'organization': 'World Bank Group',
        'url': 'https://projects.worldbank.org/en/projects-operations/procurement?srce=both',
        'source_type': 'api',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'WorldBankScraper',
        'scraper_config': {
            'url': 'https://projects.worldbank.org/en/projects-operations/procurement?srce=both',
            'api_url': 'https://search.worldbank.org/api/v2/procurement',
            'fields': 'id,title,deadline,pdate,countryname,regionname,project_name,url,borrower,sector,docty',
            'filter_query': 'docty:(Notice OR Request for Expressions of Interest OR Contract Award Notice) AND status:Active',
            'page_size': 50,
            'max_items': 300,
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'PALOP'],
            'keywords': ['consultant', 'consulting', 'technical assistance', 'expression of interest', 'contract award'],
        },
        'verify_ssl': True,
        'respect_robots_txt': True,
    },
    {
        'name': 'AfDB - Procurement Notices',
        'organization': 'African Development Bank',
        'url': 'https://www.afdb.org/en/projects-and-operations/procurement',
        'source_type': 'api',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'AfDBScraper',
        'scraper_config': {
            'url': 'https://www.afdb.org/en/projects-and-operations/procurement',
            'api_url': 'https://www.afdb.org/en/projects-and-operations/procurement',
            'max_items': 200,
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'West Africa', 'PALOP'],
            'keywords': ['consultancy', 'consultant', 'request for expressions of interest', 'procurement'],
        },
        'verify_ssl': True,
        'respect_robots_txt': True,
    },
    {
        'name': 'LuxDev - Marches',
        'organization': 'LuxDev',
        'url': 'https://luxdev.lu/fr/marches',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://luxdev.lu/fr/marches',
            'item_selectors': ['article', 'div.market', 'div.card', 'li', 'tr'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, td',
            'deadline_selector': 'time, td, .deadline',
            'organization': 'LuxDev',
            'client': 'LuxDev',
            'country': 'Africa / Lusophone Africa',
            'language': 'fr',
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'PALOP'],
            'keywords': ['consultance', 'consultant', 'services', 'marches publics'],
        },
    },
    {
        'name': 'Ghana e-GP - Procurement Notice',
        'organization': 'Ghana Electronic Procurement System',
        'url': 'https://www.ghaneps.gov.gh/epps/cft/prepareViewCfTWS.do?resourceId=2734146',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.ghaneps.gov.gh/epps/cft/prepareViewCfTWS.do?resourceId=2734146',
            'item_selectors': ['table tr', 'div.notice', 'div.content', 'li'],
            'title_selector': 'h1, h2, h3, td, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, td, div',
            'deadline_selector': 'td, time, .deadline',
            'organization': 'Ghana e-GP',
            'client': 'Ghana e-GP',
            'country': 'Ghana',
            'language': 'en',
        },
        'filters': {
            'countries': ['GHA', 'Ghana', 'West Africa'],
            'keywords': ['consultancy', 'services', 'procurement', 'tender'],
        },
    },
    {
        'name': 'East African Community - Open Procurement',
        'organization': 'East African Community',
        'url': 'https://www.eac.int/procurement-open',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.eac.int/procurement-open',
            'item_selectors': ['article', 'div.item', 'div.card', 'li', 'tr'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, td, div.introtext',
            'deadline_selector': 'time, td, .deadline',
            'organization': 'EAC',
            'client': 'East African Community',
            'country': 'East Africa',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'East Africa'],
            'keywords': ['consultancy', 'procurement', 'tender', 'technical assistance'],
        },
    },
    {
        'name': 'GIZ - Procurement Portal',
        'organization': 'Deutsche Gesellschaft fuer Internationale Zusammenarbeit (GIZ)',
        'url': 'https://ausschreibungen.giz.de/Satellite/company/welcome.do',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GIZScraper',
        'scraper_config': {
            'url': 'https://ausschreibungen.giz.de/Satellite/company/welcome.do',
            'item_selectors': ['table tr', 'div.tender', 'div.notice', 'li'],
            'organization': 'GIZ',
            'client': 'GIZ / BMZ Germany',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'PALOP'],
            'keywords': ['consulting', 'consultancy', 'technical assistance', 'services'],
        },
    },
    {
        'name': 'UNGM - Public Notices',
        'organization': 'United Nations Global Marketplace',
        'url': 'https://www.ungm.org/Public/Notice',
        'source_type': 'api',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'UNDPScraper',
        'scraper_config': {
            'url': 'https://www.ungm.org/Public/Notice',
            'api_url': 'https://www.ungm.org/Public/Notice',
            'organization': 'UNGM',
            'client': 'United Nations',
            'country': 'Africa / International',
            'language': 'en',
            'max_items': 200,
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'PALOP'],
            'keywords': ['consultancy', 'consultant', 'technical assistance', 'services'],
        },
    },
    {
        'name': 'Oracle Supplier Portal - Restricted Login',
        'organization': 'Oracle Supplier Portal',
        'url': 'https://idcs-950009d4c7154de7b9a4acb69ea50742.identity.oraclecloud.com/ui/v1/signin',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://idcs-950009d4c7154de7b9a4acb69ea50742.identity.oraclecloud.com/ui/v1/signin',
            'access': 'restricted_login',
            'notes': 'Login-gated supplier portal; keep paused until credentials and scraping permission are confirmed.',
        },
        'filters': {
            'countries': ['Africa', 'PALOP'],
            'keywords': ['supplier portal', 'procurement', 'restricted'],
            'access': ['restricted_login'],
        },
    },
    {
        'name': 'France Marches Publics - Consultation 2719648',
        'organization': 'France Marches Publics',
        'url': 'https://www.marches-publics.gouv.fr/app.php/entreprise/consultation/2719648?orgAcronyme=c8v',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.marches-publics.gouv.fr/app.php/entreprise/consultation/2719648?orgAcronyme=c8v',
            'item_selectors': ['main', 'article', 'table tr', 'div.consultation', 'li'],
            'title_selector': 'h1, h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, td, div',
            'deadline_selector': 'time, td, .date-limite',
            'organization': 'France Marches Publics',
            'client': 'France Marches Publics',
            'country': 'France / International',
            'language': 'fr',
        },
        'filters': {
            'countries': ['FR', 'Africa', 'PALOP'],
            'keywords': ['consultation', 'marches publics', 'consultance', 'services'],
        },
    },
    {
        'name': 'TendersOnTime - Lead Discovery',
        'organization': 'TendersOnTime',
        'url': 'https://www.tendersontime.com/',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.tendersontime.com/',
            'access': 'subscription',
            'notes': 'Subscription source for lead discovery; use visible titles to trigger local follow-up before enabling scraping.',
        },
        'filters': {
            'countries': ['CPV', 'GNB', 'Africa', 'PALOP'],
            'keywords': ['consultancy', 'tender', 'procurement', 'Guinea-Bissau', 'Cabo Verde'],
            'access': ['subscription'],
        },
    },
    {
        'name': 'GlobalTenders - Guinea-Bissau',
        'organization': 'GlobalTenders',
        'url': 'https://www.globaltenders.com/guinea-bissau-tenders.php',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.globaltenders.com/guinea-bissau-tenders.php',
            'access': 'subscription',
            'notes': 'Subscription source for Guinea-Bissau leads; keep paused and use titles for local validation.',
        },
        'filters': {
            'countries': ['GNB', 'Guinea-Bissau', 'PALOP', 'West Africa'],
            'keywords': ['consultancy', 'tender', 'procurement', 'services'],
            'access': ['subscription'],
        },
    },
]
