# Generated by Django 5.0.14 on 2026-05-27 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='trialing', max_length=20)),
                ('plan', models.CharField(choices=[('beta', 'Beta'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='beta', max_length=20)),
                ('organization_type', models.CharField(choices=[('consulting_firm', 'Consulting firm'), ('ngo', 'NGO'), ('donor', 'Donor'), ('government', 'Government'), ('startup', 'Startup'), ('university', 'University'), ('other', 'Other')], default='consulting_firm', max_length=40)),
                ('size', models.CharField(choices=[('solo', 'Solo'), ('small', 'Small'), ('mid_market', 'Mid-market'), ('enterprise', 'Enterprise')], default='small', max_length=20)),
                ('maturity_level', models.CharField(choices=[('early', 'Early'), ('growing', 'Growing'), ('mature', 'Mature'), ('advanced', 'Advanced')], default='growing', max_length=20)),
                ('primary_country', models.CharField(blank=True, max_length=100)),
                ('default_language', models.CharField(default='pt', max_length=10)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'plan'], name='tenants_ten_status_1a8df6_idx'), models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantIntelligenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_keywords', models.JSONField(blank=True, default=list)),
                ('excluded_keywords', models.JSONField(blank=True, default=list)),
                ('preferred_sources', models.JSONField(blank=True, default=list)),
                ('excluded_sources', models.JSONField(blank=True, default=list)),
                ('preferred_procurement_types', models.JSONField(blank=True, default=list)),
                ('minimum_score_threshold', models.PositiveSmallIntegerField(default=50)),
                ('deadline_min_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline_max_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minimum_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('maximum_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('requires_local_partner', models.BooleanField(default=False)),
                ('eligible_languages', models.JSONField(blank=True, default=list)),
                ('geographic_priority_weights', models.JSONField(blank=True, default=dict)),
                ('sector_priority_weights', models.JSONField(blank=True, default=dict)),
                ('donor_priority_weights', models.JSONField(blank=True, default=dict)),
                ('scoring_weights', models.JSONField(blank=True, default=dict)),
                ('ai_instructions', models.TextField(blank=True)),
                ('partial_intelligence_rules', models.JSONField(blank=True, default=dict)),
                ('created_from_onboarding', models.BooleanField(default=False)),
                ('last_refined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_profile', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantOnboardingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('derived_profile', models.JSONField(blank=True, default=dict)),
                ('derived_strategy', models.JSONField(blank=True, default=dict)),
                ('derived_intelligence_profile', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_onboarding_submissions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_snapshots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=250)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('organization_description', models.TextField(blank=True)),
                ('countries_of_operation', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('core_capabilities', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('past_clients', models.JSONField(blank=True, default=list)),
                ('donor_experience', models.JSONField(blank=True, default=list)),
                ('sector_experience', models.JSONField(blank=True, default=list)),
                ('team_size', models.PositiveIntegerField(default=0)),
                ('annual_bid_capacity', models.PositiveIntegerField(default=0)),
                ('average_contract_size', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('preferred_contract_size', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_objectives', models.JSONField(blank=True, default=list)),
                ('target_markets', models.JSONField(blank=True, default=list)),
                ('target_donors', models.JSONField(blank=True, default=list)),
                ('target_sectors', models.JSONField(blank=True, default=list)),
                ('target_countries', models.JSONField(blank=True, default=list)),
                ('priority_project_types', models.JSONField(blank=True, default=list)),
                ('growth_goals', models.JSONField(blank=True, default=list)),
                ('positioning_statement', models.TextField(blank=True)),
                ('risk_appetite', models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], default='balanced', max_length=20)),
                ('partnership_strategy', models.TextField(blank=True)),
                ('go_no_go_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('consultant', 'Consultant'), ('viewer', 'Viewer')], default='consultant', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant__name', 'user__email'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='tenants_ten_tenant__85750e_idx'), models.Index(fields=['user', 'status'], name='tenants_ten_user_id_21c5a3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_membership_user'),
        ),
        migrations.AddIndex(
            model_name='tenantonboardingsnapshot',
            index=models.Index(fields=['tenant', 'created_at'], name='tenants_ten_tenant__e9a664_idx'),
        ),
    ]
