# Generated by Django 5.0.14 on 2026-09-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_default_tenant_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="trial_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set only for self-service trial tenants. Null means no automatic trial expiry.",
                null=True,
            ),
        ),
    ]
