# Generated by Django 5.0.14 on 2026-05-19 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0009_firmprofile_savedfilter_and_more'),
        ('proposals', '0010_pursuitgate_gateauditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('in_review', 'In review'), ('approved', 'Approved')], default='generated', max_length=20)),
                ('generation_version', models.CharField(default='compliance_matrix_v1', max_length=40)),
                ('source_trace', models.JSONField(blank=True, default=list)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('human_override_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_compliance_matrices', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_matrix', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceMatrixRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_key', models.CharField(max_length=120)),
                ('requirement_text', models.TextField()),
                ('requirement_category', models.CharField(blank=True, max_length=40)),
                ('priority', models.CharField(choices=[('mandatory', 'Mandatory'), ('desirable', 'Desirable'), ('optional', 'Optional')], default='mandatory', max_length=20)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('partial', 'Partial'), ('covered', 'Covered'), ('waived', 'Waived')], default='missing', max_length=20)),
                ('evidence_text', models.TextField(blank=True)),
                ('evidence_link', models.URLField(blank=True)),
                ('source_type', models.CharField(default='requirement', max_length=40)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('source_trace', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('human_override', models.BooleanField(default=False)),
                ('human_override_note', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='compliance.compliancematrix')),
                ('proposal_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_rows', to='proposals.proposalsection')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['matrix', 'status'], name='compliance__matrix__3fdf33_idx'), models.Index(fields=['priority', 'status'], name='compliance__priorit_818527_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='compliancematrixrow',
            constraint=models.UniqueConstraint(fields=('matrix', 'requirement_key'), name='unique_compliance_row_per_matrix_key'),
        ),
    ]
