# Generated by Django 5.0.14 on 2026-04-20 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("daily_rate", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("specializations", models.JSONField(default=list)),
                ("education", models.TextField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                (
                    "cv_document",
                    models.FileField(blank=True, null=True, upload_to="consultants/cv/"),
                ),
                ("is_available_for_hire", models.BooleanField(default=True)),
                ("total_projects_completed", models.PositiveIntegerField(default=0)),
                ("total_proposals_won", models.PositiveIntegerField(default=0)),
                (
                    "performance_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rating from 0.00 to 5.00",
                        max_digits=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-performance_rating", "-total_projects_completed"],
            },
        ),
    ]
