# Generated by Django 5.0.14 on 2026-05-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0002_user_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='tenant_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('consultant', 'Consultant'), ('viewer', 'Viewer')], default='consultant', max_length=20),
        ),
    ]
