# Generated by Django 5.0.14 on 2026-09-17 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userinvitation_tenant_userinvitation_tenant_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvitation",
            name="organization_name",
            field=models.CharField(
                blank=True,
                help_text="Only used for self_service signup_source — the tenant name to create on verification.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="userinvitation",
            name="signup_source",
            field=models.CharField(
                choices=[("admin_invite", "Admin invite"), ("self_service", "Self service")],
                db_index=True,
                default="admin_invite",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
