# Generated by Django 5.0.14 on 2026-05-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0010_pursuitgate_gateauditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTreeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issue_tree_snapshots', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_tree_snapshots', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='IssueTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(blank=True, max_length=160, null=True)),
                ('node_type', models.CharField(choices=[('root', 'Root'), ('issue', 'Issue'), ('hypothesis', 'Hypothesis'), ('evidence', 'Evidence')], default='issue', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('hypothesis', models.TextField(blank=True)),
                ('data_needed', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('source_trace', models.JSONField(blank=True, default=list)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issue_tree_nodes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issue_tree_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='issue_tree.issuetreenode')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_tree_nodes', to='proposals.proposal')),
                ('proposal_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_tree_nodes', to='proposals.proposalsection')),
            ],
            options={
                'ordering': ['proposal_id', 'parent_id', 'order', 'id'],
                'indexes': [models.Index(fields=['proposal', 'parent'], name='issue_tree__proposa_044205_idx'), models.Index(fields=['proposal', 'status'], name='issue_tree__proposa_4c23f7_idx'), models.Index(fields=['proposal', 'node_type'], name='issue_tree__proposa_0ae869_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='issuetreenode',
            constraint=models.UniqueConstraint(fields=('proposal', 'source_key'), name='unique_issue_tree_node_source_key_per_proposal'),
        ),
        migrations.AddConstraint(
            model_name='issuetreesnapshot',
            constraint=models.UniqueConstraint(fields=('proposal', 'version'), name='unique_issue_tree_snapshot_version_per_proposal'),
        ),
    ]
