# Generated by Django 5.0.14 on 2026-05-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('demand_spike', 'Demand spike detected'), ('budget_shift', 'Budget concentration shift'), ('seasonal_onset', 'Seasonal demand onset')], max_length=30)),
                ('country_iso', models.CharField(blank=True, db_index=True, max_length=20)),
                ('sector_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('message', models.TextField()),
                ('data_snapshot', models.JSONField(blank=True, default=dict)),
                ('acknowledged', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['signal_type', 'country_iso', 'sector_code'], name='analytics_m_signal__6d8781_idx'), models.Index(fields=['acknowledged', 'created_at'], name='analytics_m_acknowl_7bad3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictiveMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(db_index=True, max_length=100)),
                ('country_iso', models.CharField(blank=True, db_index=True, max_length=20)),
                ('sector_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('forecast_horizon_months', models.PositiveSmallIntegerField(default=3)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['valid_until', 'metric_key'], name='predictive_metric_valid_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='predictivemetric',
            constraint=models.UniqueConstraint(fields=('metric_key', 'country_iso', 'sector_code', 'forecast_horizon_months'), name='unique_predictive_metric_scope_horizon'),
        ),
    ]
