import type {
  TeamStats,
  PipelinePhase,
  InternalTeamMember,
  Consultant,
  ProjectTeam,
} from '@/types/teams';

export const teamStats: TeamStats = {
  internalMembers: 9,
  externalConsultants: 8,
  activeProjects: 1,
  averageRating: 4.4,
};

export const pipelinePhases: PipelinePhase[] = [
  { phase: 'Prospeccao', members: 1 },
  { phase: 'Montagem Proposta', members: 8 },
  { phase: 'Metodologia', members: 2 },
  { phase: 'Orcamento', members: 1 },
  { phase: 'Redacao/Revisao', members: 6 },
  { phase: 'Quality Assurance', members: 4 },
  { phase: 'Coordenacao', members: 2 },
  { phase: 'Projeto Ganho', members: 1 },
];

export const internalTeamMembers: InternalTeamMember[] = [
  {
    id: 'int-1',
    name: 'Miguel Rodrigues',
    email: 'miguel.rodrigues@consultpro.pt',
    role: 'Coordenador',
    phase: 'Coordenacao',
    department: 'Gestao de Propostas',
    skills: ['Gestao de Projetos', 'Coordenacao', 'Estrategia'],
    availability: 'busy',
    projectsCount: 12,
    joinedAt: '2022-03-15',
  },
  {
    id: 'int-2',
    name: 'Ana Pereira',
    email: 'ana.pereira@consultpro.pt',
    role: 'Prospetora',
    phase: 'Prospeccao',
    department: 'Business Development',
    skills: ['Prospeccao', 'Negociacao', 'Relacoes Internacionais'],
    availability: 'available',
    projectsCount: 8,
    joinedAt: '2023-01-10',
  },
  {
    id: 'int-3',
    name: 'Carlos Santos',
    email: 'carlos.santos@consultpro.pt',
    role: 'Metodologista',
    phase: 'Metodologia',
    department: 'Metodologia',
    skills: ['Metodologia', 'Pesquisa', 'Avaliacao'],
    availability: 'available',
    projectsCount: 15,
    joinedAt: '2021-06-20',
  },
  {
    id: 'int-4',
    name: 'Mariana Costa',
    email: 'mariana.costa@consultpro.pt',
    role: 'Orcamentista',
    phase: 'Orcamento',
    department: 'Financeiro',
    skills: ['Orcamentacao', 'Financas', 'Analise de Custos'],
    availability: 'busy',
    projectsCount: 20,
    joinedAt: '2020-11-05',
  },
  {
    id: 'int-5',
    name: 'Sofia Almeida',
    email: 'sofia.almeida@consultpro.pt',
    role: 'Redatora',
    phase: 'Redacao/Revisao',
    department: 'Redacao',
    skills: ['Redacao Tecnica', 'Revisao', 'Comunicacao'],
    availability: 'available',
    projectsCount: 18,
    joinedAt: '2021-09-12',
  },
  {
    id: 'int-6',
    name: 'Pedro Fonseca',
    email: 'pedro.fonseca@consultpro.pt',
    role: 'QA',
    phase: 'Quality Assurance',
    department: 'Qualidade',
    skills: ['Quality Assurance', 'Revisao', 'Controlo de Qualidade'],
    availability: 'available',
    projectsCount: 10,
    joinedAt: '2023-04-01',
  },
  {
    id: 'int-7',
    name: 'Ines Marques',
    email: 'ines.marques@consultpro.pt',
    role: 'Montadora',
    phase: 'Montagem Proposta',
    department: 'Producao',
    skills: ['Montagem', 'Formatacao', 'Design Documental'],
    availability: 'busy',
    projectsCount: 14,
    joinedAt: '2022-08-15',
  },
  {
    id: 'int-8',
    name: 'Rui Barbosa',
    email: 'rui.barbosa@consultpro.pt',
    role: 'Gestor de Projeto',
    phase: 'Projeto Ganho',
    department: 'Gestao de Projetos',
    skills: ['Gestao de Projetos', 'Lideranca', 'Stakeholder Management'],
    availability: 'busy',
    projectsCount: 7,
    joinedAt: '2023-02-20',
  },
  {
    id: 'int-9',
    name: 'Catarina Lopes',
    email: 'catarina.lopes@consultpro.pt',
    role: 'Revisora',
    phase: 'Redacao/Revisao',
    department: 'Qualidade',
    skills: ['Revisao', 'Edicao', 'Linguistica'],
    availability: 'available',
    projectsCount: 11,
    joinedAt: '2022-11-30',
  },
];

export const consultants: Consultant[] = [
  {
    id: 'ext-1',
    name: 'Amadou Diallo',
    email: 'amadou.diallo@consultant.com',
    seniority: 'senior',
    seniorityLabel: 'Senior',
    availability: 'available',
    location: 'Dakar, Senegal',
    education: 'PhD em Economia do Desenvolvimento',
    yearsExperience: 18,
    projectsCompleted: 45,
    dailyRate: 850,
    currency: 'USD',
    rating: 4.8,
    skills: ['Economia', 'Avaliacao de Impacto', 'Estatistica', 'Gestao de Projetos'],
    languages: ['Frances', 'Ingles', 'Wolof'],
    sectors: ['Saude', 'Agricultura', 'Governanca'],
    lastProject: { name: 'Projeto Banco Mundial - Senegal', date: '2024-12-15' },
  },
  {
    id: 'ext-2',
    name: 'Fernando Lopes',
    email: 'fernando.lopes@consultant.com',
    seniority: 'senior',
    seniorityLabel: 'Senior',
    availability: 'busy',
    location: 'Lisboa, Portugal',
    education: 'MSc em Engenharia Civil',
    yearsExperience: 22,
    projectsCompleted: 38,
    dailyRate: 900,
    currency: 'USD',
    rating: 4.7,
    skills: ['Infraestruturas', 'Engenharia', 'Gestao de Obras', 'Orcamentacao'],
    languages: ['Portugues', 'Ingles', 'Espanhol'],
    sectors: ['Infraestruturas', 'Ambiente'],
    lastProject: { name: 'Projeto UE - Angola', date: '2025-01-20' },
  },
  {
    id: 'ext-3',
    name: 'Lucia Fernandez',
    email: 'lucia.fernandez@consultant.com',
    seniority: 'senior',
    seniorityLabel: 'Senior',
    availability: 'available',
    location: 'Madrid, Espanha',
    education: 'PhD em Educacao Comparada',
    yearsExperience: 16,
    projectsCompleted: 32,
    dailyRate: 800,
    currency: 'USD',
    rating: 4.6,
    skills: ['Educacao', 'Formacao de Formadores', 'Curriculum Development', 'Avaliacao'],
    languages: ['Espanhol', 'Ingles', 'Portugues'],
    sectors: ['Educacao', 'Genero'],
    lastProject: { name: 'Projeto UNICEF - Brasil', date: '2024-11-10' },
  },
  {
    id: 'ext-4',
    name: 'Kwame Asante',
    email: 'kwame.asante@consultant.com',
    seniority: 'senior',
    seniorityLabel: 'Senior',
    availability: 'available',
    location: 'Accra, Gana',
    education: 'MSc em Saude Publica',
    yearsExperience: 20,
    projectsCompleted: 50,
    dailyRate: 820,
    currency: 'USD',
    rating: 4.9,
    skills: ['Saude Publica', 'Epidemiologia', 'Sistemas de Saude', 'Formacao'],
    languages: ['Ingles', 'Twi', 'Frances'],
    sectors: ['Saude', 'Governanca'],
    lastProject: { name: 'Projeto GAVI - Gana', date: '2025-02-05' },
  },
  {
    id: 'ext-5',
    name: 'Amina Hassan',
    email: 'amina.hassan@consultant.com',
    seniority: 'mid',
    seniorityLabel: 'Mid-Level',
    availability: 'available',
    location: 'Nairobi, Quenia',
    education: 'MSc em Desenvolvimento Rural',
    yearsExperience: 8,
    projectsCompleted: 18,
    dailyRate: 550,
    currency: 'USD',
    rating: 4.3,
    skills: ['Agricultura', 'Desenvolvimento Rural', 'Monitoramento', 'Avaliacao'],
    languages: ['Ingles', 'Swahili'],
    sectors: ['Agricultura', 'Ambiente'],
    lastProject: { name: 'Projeto FAO - Quenia', date: '2024-10-20' },
  },
  {
    id: 'ext-6',
    name: 'Tiago Matos',
    email: 'tiago.matos@consultant.com',
    seniority: 'mid',
    seniorityLabel: 'Mid-Level',
    availability: 'busy',
    location: 'Porto, Portugal',
    education: 'MSc em Gestao Ambiental',
    yearsExperience: 7,
    projectsCompleted: 15,
    dailyRate: 500,
    currency: 'USD',
    rating: 4.2,
    skills: ['Ambiente', 'Sustentabilidade', 'Avaliacao Ambiental', 'Climate Change'],
    languages: ['Portugues', 'Ingles'],
    sectors: ['Ambiente', 'Infraestruturas'],
    lastProject: { name: 'Projeto GIZ - Mocambique', date: '2025-01-15' },
  },
  {
    id: 'ext-7',
    name: 'Catarina Mendes',
    email: 'catarina.mendes@consultant.com',
    seniority: 'mid',
    seniorityLabel: 'Mid-Level',
    availability: 'available',
    location: 'Bissau, Guine-Bissau',
    education: 'MSc em Direitos Humanos',
    yearsExperience: 9,
    projectsCompleted: 20,
    dailyRate: 520,
    currency: 'USD',
    rating: 4.4,
    skills: ['Genero', 'Direitos Humanos', 'Inclusao Social', 'Formacao'],
    languages: ['Portugues', 'Ingles', 'Crioulo'],
    sectors: ['Genero', 'Educacao', 'Governanca'],
    lastProject: { name: 'Projeto UNFPA - GB', date: '2024-09-30' },
  },
  {
    id: 'ext-8',
    name: 'Bruno Correia',
    email: 'bruno.correia@consultant.com',
    seniority: 'junior',
    seniorityLabel: 'Junior',
    availability: 'available',
    location: 'Luanda, Angola',
    education: 'Licenciatura em Economia',
    yearsExperience: 3,
    projectsCompleted: 6,
    dailyRate: 280,
    currency: 'USD',
    rating: 4.1,
    skills: ['Analise Economica', 'Pesquisa', 'Relatorios', 'Dados'],
    languages: ['Portugues', 'Ingles'],
    sectors: ['Governanca', 'Economia'],
    lastProject: { name: 'Projeto Banco Africano - Angola', date: '2025-01-10' },
  },
];

export const projectTeams: ProjectTeam[] = [
  {
    id: 'proj-1',
    name: 'Proposta FAO Cabo Verde',
    client: 'FAO',
    phase: 'Redacao/Revisao',
    status: 'in_proposal',
    internalMembers: [
      { id: 'int-1', name: 'Miguel Rodrigues', role: 'Coordenador', type: 'internal' },
      { id: 'int-5', name: 'Sofia Almeida', role: 'Redatora', type: 'internal' },
      { id: 'int-3', name: 'Carlos Santos', role: 'Metodologista', type: 'internal' },
      { id: 'int-4', name: 'Mariana Costa', role: 'Orcamentista', type: 'internal' },
      { id: 'int-6', name: 'Pedro Fonseca', role: 'QA', type: 'internal' },
    ],
    externalMembers: [],
  },
  {
    id: 'proj-2',
    name: 'Projeto UNICEF Mocambique',
    client: 'UNICEF',
    phase: 'Projeto Ganho',
    status: 'won',
    manager: 'Miguel Rodrigues',
    startDate: '2025-01-15',
    internalMembers: [
      { id: 'int-1', name: 'Miguel Rodrigues', role: 'Gestor de Projeto', type: 'internal' },
      { id: 'int-8', name: 'Rui Barbosa', role: 'Coordenador Tecnico', type: 'internal' },
    ],
    externalMembers: [
      { id: 'ext-4', name: 'Kwame Asante', role: 'Especialista em Saude', type: 'external' },
      { id: 'ext-6', name: 'Tiago Matos', role: 'Especialista Ambiental', type: 'external' },
    ],
  },
];
