"""
Management command to initialize scraping sources for consultpro.cv.
Populates the database with pre-configured sources focused on Cabo Verde and Africa.

Usage:
    python manage.py setup_scraping_sources
"""
from django.core.management.base import BaseCommand
from apps.scraping.models import ScrapingSource


DEFAULT_SOURCES = [
    {
        'name': 'UGPE - Concursos Cabo Verde',
        'organization': 'UGPE',
        'url': 'https://ugpe.gov.cv/concursos',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'UGPEScraper',
        'scraper_config': {
            'url': 'https://ugpe.gov.cv/concursos',
            'item_selectors': [
                'table.concursos-table tbody tr',
                'div.concurso-item',
                'div.opportunity-item',
            ],
        },
        'filters': {
            'countries': ['CPV'],
            'keywords': ['consultoria', 'consultor', 'consultant'],
        },
    },
    {
        'name': 'ECREEE - Procurement Notices',
        'organization': 'ECREEE / CEDEAO',
        'url': 'https://www.ecreee.org/category/procurement-notices/',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'ECREEEScraper',
        'scraper_config': {
            'url': 'https://www.ecreee.org/category/procurement-notices/',
            'item_selectors': [
                'article.post',
                'div.post',
                'article.type-post',
            ],
        },
        'filters': {
            'countries': ['CPV', 'GHA', 'SEN', 'NGA'],
            'keywords': ['consultancy', 'consultant', 'expert', 'advisor'],
        },
    },
    {
        'name': 'World Bank - Operational Consulting',
        'organization': 'World Bank Group',
        'url': 'https://www.worldbank.org/en/about/corporate-procurement/business-opportunities/operational-consulting-opportunities',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'WorldBankScraper',
        'scraper_config': {
            'url': 'https://www.worldbank.org/en/about/corporate-procurement/business-opportunities/operational-consulting-opportunities',
            'api_url': 'https://search.worldbank.org/api/v2/procurement',
            'fields': 'id,title,deadline,pdate,countryname,regionname,project_name,url,borrower,sector,docty',
            'filter_query': 'docty:Notice AND status:Active',
            'page_size': 50,
            'max_items': 200,
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'advisory', 'technical assistance'],
        },
    },
    {
        'name': 'AfDB - Consultant Vacancies',
        'organization': 'African Development Bank',
        'url': 'https://www.afdb.org/en/about-us/careers/current-vacancies/consultants',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'AfDBScraper',
        'scraper_config': {
            'url': 'https://www.afdb.org/en/about-us/careers/current-vacancies/consultants',
            'api_url': 'https://www.afdb.org/api/v1/node/procurement',
            'rss_url': 'https://www.afdb.org/en/projects-and-operations/procurement/rss',
            'page_size': 50,
            'page': 0,
            'status': 1,
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'expert'],
        },
    },
    {
        'name': 'UNDP - Job Opportunities',
        'organization': 'UNDP',
        'url': 'https://jobs.undp.org/cj_view_jobs.cfm',
        'source_type': 'job_board',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'UNDPScraper',
        'scraper_config': {
            'url': 'https://jobs.undp.org/cj_view_jobs.cfm',
            'api_url': 'https://www.ungm.org/Public/Notice',
            'rss_url': 'https://procurement-notices.undp.org/feed.cfm?po_filter=all',
            'notice_type': 0,
            'page_size': 50,
            'max_items': 200,
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'international consultant'],
        },
    },
    {
        'name': 'LuxDev - Call for Tenders',
        'organization': 'LuxDev',
        'url': 'https://luxdev.lu/en/tenders/call-tenders',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'LuxDevScraper',
        'scraper_config': {
            'urls': [
                'https://luxdev.lu/en/tenders/call-tenders',
                'https://luxdev.lu/en/tenders/calls-proposals',
            ],
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'ACP'],
            'keywords': ['consultant', 'tender', 'proposal', 'expertise'],
        },
    },
    {
        'name': 'FAO - Cabo Verde Procurement',
        'organization': 'FAO',
        'url': 'https://www.fao.org/cabo-verde/fao-au-cabo-verde/procurement/en/',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.fao.org/cabo-verde/fao-au-cabo-verde/procurement/en/',
            'item_selectors': ['div.item', 'article', 'tr', 'li'],
            'title_selector': 'h3, h4, a, strong',
            'link_selector': 'a[href]',
            'description_selector': 'p, .description',
            'deadline_selector': '.deadline, .date',
            'organization': 'FAO',
            'client': 'FAO Cabo Verde',
            'country': 'Cabo Verde',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV'],
            'keywords': ['consultant', 'consultancy', 'procurement'],
        },
    },
    {
        'name': 'Instituto Camões - Oportunidades',
        'organization': 'Instituto Camões, I.P.',
        'url': 'https://www.instituto-camoes.pt/activity/oportunidades',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.instituto-camoes.pt/activity/oportunidades',
            'item_selectors': ['article', 'div.item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, .summary',
            'organization': 'Instituto Camões',
            'client': 'Instituto Camões, I.P.',
            'country': 'PALOP',
            'language': 'pt',
        },
        'filters': {
            'countries': ['CPV', 'AO', 'MZ', 'GW', 'ST', 'PT'],
            'keywords': ['consultor', 'consultoria', 'especialista', 'perito'],
        },
    },
    {
        'name': 'AECID - Cooperação Cabo Verde',
        'organization': 'AECID',
        'url': 'https://www.aecid.es',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.aecid.es',
            'item_selectors': ['article', 'div.item', 'tr'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'AECID',
            'client': 'Agência Espanhola de Cooperação',
            'country': 'Cabo Verde',
            'language': 'es',
        },
        'filters': {
            'countries': ['CPV'],
            'keywords': ['consultor', 'consultoria', 'cooperación'],
        },
    },
    {
        'name': 'ECOWAS / CEDEAO - Procurement',
        'organization': 'ECOWAS',
        'url': 'https://www.ecowas.int',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.ecowas.int',
            'item_selectors': ['article', 'div.item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'ECOWAS / CEDEAO',
            'client': 'ECOWAS',
            'country': 'Regional',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'West Africa'],
            'keywords': ['consultant', 'consultancy', 'procurement'],
        },
    },
    {
        'name': 'dgMarket - Global Tenders',
        'organization': 'dgMarket',
        'url': 'https://www.dgmarket.com',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.dgmarket.com',
            'item_selectors': ['div.tender-item', 'tr', 'article'],
            'title_selector': 'h3, a.tender-title',
            'link_selector': 'a[href]',
            'description_selector': '.description, p',
            'organization': 'dgMarket',
            'client': 'Various',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'advisory'],
        },
    },
    # === EU Grants & Multilateral Sources ===
    {
        'name': 'EU Funding & Tenders Portal',
        'organization': 'European Commission',
        'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/calls-for-proposals;type=1;status=31,8',
        'source_type': 'api',
        'status': 'paused',  # React SPA — needs API integration (EU Open Data Portal)
        'scrape_frequency': 'weekly',
        'scraper_class': 'EUFundingScraper',
        'scraper_config': {
            'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/calls-for-proposals;type=1;status=31,8',
            'reference_data_url': 'https://ec.europa.eu/info/funding-tenders/opportunities/data/referenceData/grantProgramme',
            'item_selectors': ['div.topic-item', 'tr', 'article', 'li'],
            'title_selector': 'h3, h4, a, strong',
            'link_selector': 'a[href]',
            'description_selector': 'p, .description',
            'deadline_selector': '.deadline, .date, .end-date',
            'organization': 'European Commission',
            'client': 'EU',
            'country': 'Africa / International',
            'language': 'en',
            'source_category': 'eu_grants',
        },
        'filters': {
            'countries': ['Africa', 'CPV'],
            'keywords': ['consultant', 'consultancy', 'expert', 'technical assistance'],
            'programmes': [
                'NDICI', 'Global Gateway', 'ARISE', 'EU-AITF',
                'Intra-Africa Mobility', 'AU-EU Youth Lab', 'Digital Innovation',
            ],
        },
    },
    {
        'name': 'DG INTPA - EU International Partnerships',
        'organization': 'European Commission - DG INTPA',
        'url': 'https://international-partnerships.ec.europa.eu',
        'source_type': 'portal',
        'status': 'paused',  # React SPA — needs API integration
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://international-partnerships.ec.europa.eu',
            'item_selectors': ['article', 'div.item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'European Commission',
            'client': 'DG INTPA',
            'country': 'Africa',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV'],
            'keywords': ['grant', 'funding', 'consultancy', 'expert'],
            'sectors': ['green energy', 'health', 'digital', 'education', 'youth'],
        },
    },
    {
        'name': 'TED - Tenders Electronic Daily',
        'organization': 'Publications Office of the EU',
        'url': 'https://ted.europa.eu',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://ted.europa.eu',
            'item_selectors': ['div.notice', 'tr', 'article'],
            'title_selector': 'h3, a.notice-title',
            'link_selector': 'a[href]',
            'description_selector': '.description, p',
            'organization': 'EU',
            'client': 'Various EU Institutions',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'technical assistance'],
        },
    },
    {
        'name': 'EIB - European Investment Bank',
        'organization': 'EIB',
        'url': 'https://www.eib.org/en/about/procurement/calls/index.htm',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.eib.org/en/about/procurement/calls/index.htm',
            'item_selectors': [
                'table.standard-table tbody tr',
                'div.eib-component__tender-item',
                'div.tender-item',
                'article.tender',
                'li.tender',
                'tr',
            ],
            'title_selector': 'td:nth-child(2) a, td:first-child a, h3 a, h4 a, a',
            'link_selector': 'a[href]',
            'description_selector': 'td:nth-child(2), p, .description',
            'deadline_selector': 'td:last-child, .deadline, .closing-date',
            'reference_selector': 'td:first-child, .reference',
            'organization': 'EIB',
            'client': 'European Investment Bank',
            'country': 'Africa / International',
            'language': 'en',
            'reject_title_patterns': [
                r'^The EIB (and|at|in|Group)\b',
                r'^EIB (Group|Board|Annual|Report|Press|Strategy)',
                r'\b(annual report|press release|speech|interview|publication)\b',
            ],
        },
        'filters': {
            'countries': ['Africa', 'CPV'],
            'keywords': ['consultant', 'consulting', 'advisory', 'tender', 'procurement',
                         'infrastructure', 'energy', 'expression of interest'],
        },
    },
    {
        'name': 'Devex - Development Jobs & Tenders',
        'organization': 'Devex',
        'url': 'https://www.devex.com',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.devex.com',
            'item_selectors': ['div.job-item', 'article', 'tr'],
            'title_selector': 'h3, a.job-title',
            'link_selector': 'a[href]',
            'description_selector': 'p, .description',
            'organization': 'Devex',
            'client': 'Various',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'advisor'],
        },
    },
    # === Expanded Cabo Verde / Africa Consulting Sources ===
    {
        'name': 'AFD - Procurement',
        'organization': 'Agence Francaise de Developpement',
        'url': 'https://www.afd.fr/en/procurement',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.afd.fr/en/procurement',
            'item_selectors': ['article', 'div.item', 'tr', 'li'],
            'title_selector': 'h2, h3, a, strong',
            'link_selector': 'a[href]',
            'description_selector': 'p, .description',
            'deadline_selector': '.deadline, .date',
            'organization': 'AFD',
            'client': 'Agence Francaise de Developpement',
            'country': 'Africa',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'appel d offres', 'technical assistance'],
            'sectors': ['blue economy', 'fisheries', 'infrastructure', 'energy'],
        },
    },
    {
        'name': 'Fundacao Calouste Gulbenkian - Financiamentos',
        'organization': 'Fundacao Calouste Gulbenkian',
        'url': 'https://gulbenkian.pt/pt/ajuda/financiamentos/',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://gulbenkian.pt/pt/ajuda/financiamentos/',
            'item_selectors': ['article', 'div.item', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, .summary',
            'organization': 'Fundacao Calouste Gulbenkian',
            'client': 'Fundacao Calouste Gulbenkian',
            'country': 'Portugal / PALOP',
            'language': 'pt',
        },
        'filters': {
            'countries': ['CPV', 'PT', 'PALOP'],
            'keywords': ['financiamento', 'bolsa', 'consultoria', 'desenvolvimento'],
        },
    },
    {
        'name': 'UNGM - United Nations Global Marketplace',
        'organization': 'United Nations',
        'url': 'https://www.ungm.org/Public/Notice',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.ungm.org/Public/Notice',
            'item_selectors': ['tr', 'div.notice', 'article'],
            'title_selector': 'a, h3, h4',
            'link_selector': 'a[href]',
            'description_selector': 'p, td',
            'deadline_selector': '.deadline, td',
            'organization': 'United Nations',
            'client': 'UN Agencies',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'technical assistance', 'evaluation'],
        },
    },
    {
        'name': 'UNOPS - Careers Africa',
        'organization': 'UNOPS',
        'url': 'https://www.unops.org/careers',
        'source_type': 'job_board',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.unops.org/careers',
            'item_selectors': ['article', 'div.job-item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'UNOPS',
            'client': 'UNOPS',
            'country': 'Africa',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'specialist', 'advisor', 'infrastructure'],
        },
    },
    {
        'name': 'UNICEF - Careers and Consultancies',
        'organization': 'UNICEF',
        'url': 'https://www.unicef.org/careers',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.unicef.org/careers',
            'item_selectors': ['article', 'div.job-item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'UNICEF',
            'client': 'UNICEF',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'evaluation', 'specialist'],
            'sectors': ['health', 'education', 'child protection', 'social policy'],
        },
    },
    {
        'name': 'World Bank - Projects Cabo Verde',
        'organization': 'World Bank Group',
        'url': 'https://projects.worldbank.org',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'WorldBankScraper',
        'scraper_config': {
            'url': 'https://projects.worldbank.org',
            'api_url': 'https://search.worldbank.org/api/v2/projects',
            'format': 'json',
            'countrycode_exact': 'CV',
            'page_size': 50,
            'max_items': 100,
        },
        'filters': {
            'countries': ['CPV'],
            'keywords': ['consultant', 'consulting services', 'technical assistance', 'project'],
            'sectors': ['digital', 'tourism', 'health', 'blue economy', 'governance'],
        },
    },
    {
        'name': 'Development Business - Tenders',
        'organization': 'Development Business',
        'url': 'https://developmentbusiness.un.org',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://developmentbusiness.un.org',
            'item_selectors': ['article', 'div.notice', 'tr'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, .description',
            'deadline_selector': '.deadline, .date',
            'organization': 'Development Business',
            'client': 'Multilateral Development Banks',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'expression of interest', 'request for proposals'],
        },
    },
    {
        'name': 'Impactpool - International Development Jobs',
        'organization': 'Impactpool',
        'url': 'https://www.impactpool.org',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.impactpool.org',
            'item_selectors': ['article', 'div.job-item', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'Impactpool',
            'client': 'Various',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'advisor', 'expert'],
        },
    },
    {
        'name': 'UNjobnet - UN Jobs',
        'organization': 'UNjobnet',
        'url': 'https://www.unjobnet.org',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.unjobnet.org',
            'item_selectors': ['article', 'div.job-item', 'tr'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'UNjobnet',
            'client': 'UN Agencies',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'AFRITAC', 'technical assistance'],
        },
    },
    {
        'name': 'UN Talent - Consulting Opportunities',
        'organization': 'UN Talent',
        'url': 'https://untalent.org',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://untalent.org',
            'item_selectors': ['article', 'div.job-item', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'UN Talent',
            'client': 'UN Agencies',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consulting', 'volunteer', 'specialist'],
        },
    },
    {
        'name': 'ReliefWeb - Jobs',
        'organization': 'ReliefWeb',
        'url': 'https://reliefweb.int/jobs',
        'source_type': 'job_board',
        'status': 'paused',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://reliefweb.int/jobs',
            'item_selectors': ['article', 'div.rw-river-article', 'li'],
            'title_selector': 'h3, h2, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'ReliefWeb',
            'client': 'Humanitarian Organizations',
            'country': 'International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': ['consultant', 'consultancy', 'advisor', 'evaluation'],
            'sectors': ['humanitarian', 'health', 'resilience', 'development'],
        },
    },
    {
        'name': 'CILSS - Sahel Opportunities',
        'organization': 'CILSS',
        'url': 'https://www.cilss.int',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.cilss.int',
            'item_selectors': ['article', 'div.item', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'CILSS',
            'client': 'CILSS',
            'country': 'Sahel / West Africa',
            'language': 'fr',
        },
        'filters': {
            'countries': ['CPV', 'West Africa', 'Sahel'],
            'keywords': ['consultant', 'consultance', 'expert', 'securite alimentaire'],
            'sectors': ['food security', 'environment', 'climate resilience'],
        },
    },
    {
        'name': 'BOAD - Procurement',
        'organization': 'BOAD',
        'url': 'https://www.boad.org',
        'source_type': 'portal',
        'status': 'paused',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.boad.org',
            'item_selectors': ['article', 'div.item', 'tr', 'li'],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p',
            'organization': 'BOAD',
            'client': 'West African Development Bank',
            'country': 'West Africa',
            'language': 'fr',
        },
        'filters': {
            'countries': ['CPV', 'West Africa'],
            'keywords': ['consultant', 'consultance', 'appel d offres', 'expert'],
            'sectors': ['infrastructure', 'energy', 'agriculture', 'governance'],
        },
    },

    # ── GRANTS & FINANCING ─────────────────────────────────────────────────
    {
        'name': 'GIZ - International Tenders',
        'organization': 'Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ)',
        'url': 'https://www.giz.de/en/mediacenter/107225.html',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GIZScraper',
        'scraper_config': {
            'url': 'https://www.giz.de/en/mediacenter/107225.html',
            'jobs_url': 'https://www.giz.de/en/jobs/jobs.html',
            'item_selectors': [
                'div.teaserbox',
                'article.tender',
                'div.result-item',
                'li.result',
                'tr',
            ],
            'title_selector': 'h2, h3, h4, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.description, div.teaser-text',
            'deadline_selector': '.deadline, .date, time, td:last-child',
            'organization': 'GIZ',
            'client': 'GIZ / BMZ Germany',
            'country': 'Africa / International',
            'language': 'en',
            'source_category': 'bilateral_procurement',
        },
        'filters': {
            'countries': ['Africa', 'CPV', 'PALOP'],
            'keywords': ['consultant', 'consultancy', 'expert', 'advisory', 'technical assistance', 'framework', 'tender'],
            'sectors': ['governance', 'health', 'education', 'environment', 'infrastructure', 'agriculture'],
        },
    },
    {
        'name': 'AFD - Appels d\'Offres / Calls for Tenders',
        'organization': 'Agence Française de Développement (AFD)',
        'url': 'https://www.afd.fr/en/calls-for-tenders',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.afd.fr/en/calls-for-tenders',
            'item_selectors': [
                'article',
                'div.tender-item',
                'div.appel-offre',
                'li.node',
                'div.card',
            ],
            'title_selector': 'h2, h3, h4, a.title, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.field-body, div.description',
            'deadline_selector': '.field-deadline, .date, time, span.date',
            'organization': 'AFD',
            'client': 'Agence Française de Développement',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV', 'PALOP', 'Guinea-Bissau', 'Senegal', 'Mauritania'],
            'keywords': ['consultant', 'consultancy', 'expertise', 'tender', 'advisory', 'mission'],
            'sectors': ['infrastructure', 'energy', 'agriculture', 'urban', 'health', 'education'],
        },
    },
    {
        'name': 'IFAD - Procurement Notices',
        'organization': 'International Fund for Agricultural Development (IFAD)',
        'url': 'https://www.ifad.org/en/procurement',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.ifad.org/en/procurement',
            'item_selectors': [
                'div.procurement-item',
                'article',
                'tr',
                'li',
                'div.node',
            ],
            'title_selector': 'h2, h3, h4, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.body',
            'deadline_selector': '.deadline, .closing-date, td:last-child, time',
            'organization': 'IFAD',
            'client': 'International Fund for Agricultural Development',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV'],
            'keywords': ['consultant', 'consultancy', 'expert', 'advisory', 'agricultural', 'rural'],
            'sectors': ['agriculture', 'rural development', 'food security', 'environment'],
        },
    },
    {
        'name': 'EU INTPA - Calls for Proposals (Africa)',
        'organization': 'European Commission / DG INTPA',
        'url': 'https://ec.europa.eu/international-partnerships/funding/calls-proposals_en',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://ec.europa.eu/international-partnerships/funding/calls-proposals_en',
            'item_selectors': [
                'article',
                'div.ecl-content-item',
                'div.result-item',
                'li',
                'tr',
            ],
            'title_selector': 'h2, h3, a.ecl-link, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.ecl-description',
            'deadline_selector': 'time, .date, .deadline',
            'organization': 'EU / DG INTPA',
            'client': 'European Commission',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV', 'PALOP'],
            'keywords': ['call for proposals', 'grant', 'consultant', 'technical assistance', 'civil society'],
            'sectors': ['governance', 'democracy', 'human rights', 'development', 'civil society'],
        },
    },

    # ── CIVIL SOCIETY & CIVIC SECTOR ───────────────────────────────────────
    {
        'name': 'Hivos - Open Calls & Funding',
        'organization': 'Hivos International',
        'url': 'https://hivos.org/calls/',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://hivos.org/calls/',
            'item_selectors': [
                'article',
                'div.post',
                'div.call-item',
                'li.post',
            ],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.excerpt, div.entry-summary',
            'deadline_selector': '.deadline, .date, time',
            'organization': 'Hivos',
            'client': 'Hivos International',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV'],
            'keywords': ['call', 'grant', 'funding', 'civil society', 'organisations', 'consultant', 'expert'],
            'sectors': ['civil society', 'democracy', 'human rights', 'environment', 'digital rights', 'gender'],
        },
    },
    {
        'name': 'Open Society Foundations - Grants',
        'organization': 'Open Society Foundations (OSF)',
        'url': 'https://www.opensocietyfoundations.org/grants',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.opensocietyfoundations.org/grants',
            'item_selectors': [
                'article',
                'div.grant-item',
                'div.funding-opportunity',
                'li',
            ],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.description, div.body',
            'deadline_selector': '.deadline, .date, time',
            'organization': 'Open Society Foundations',
            'client': 'OSF',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV', 'PALOP'],
            'keywords': ['grant', 'funding', 'civil society', 'democracy', 'human rights', 'governance', 'open society'],
            'sectors': ['civil society', 'democracy', 'human rights', 'media', 'justice', 'public health'],
        },
    },
    {
        'name': 'Reliefweb - Tenders & Contracts (Africa)',
        'organization': 'Reliefweb / OCHA',
        'url': 'https://reliefweb.int/jobs?source=0&type=0&country=CVD',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://reliefweb.int/jobs?source=0&type=0',
            'item_selectors': [
                'article',
                'div.job-item',
                'li.river-item',
                'div.content-list-item',
            ],
            'title_selector': 'h3, h4, a.title, a',
            'link_selector': 'a[href]',
            'description_selector': 'div.country, div.type, p, div.summary',
            'deadline_selector': '.deadline, .date, time',
            'organization': 'Various (Reliefweb)',
            'client': 'Various NGOs / UN Agencies',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV', 'Guinea-Bissau', 'Senegal'],
            'keywords': ['consultant', 'consultancy', 'expert', 'advisor', 'evaluation', 'assessment', 'baseline'],
            'sectors': ['humanitarian', 'development', 'civil society', 'health', 'education', 'WASH', 'food security'],
        },
    },
    {
        'name': 'African Union - Procurement & Tenders',
        'organization': 'African Union Commission (AUC)',
        'url': 'https://au.int/en/tenders',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://au.int/en/tenders',
            'item_selectors': [
                'article',
                'div.tender-item',
                'table tbody tr',
                'li',
            ],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, td, div.body',
            'deadline_selector': 'td:last-child, .date, time',
            'organization': 'African Union',
            'client': 'African Union Commission',
            'country': 'Africa',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV'],
            'keywords': ['consultant', 'consultancy', 'expert', 'tender', 'procurement', 'advisory'],
            'sectors': ['governance', 'peace', 'development', 'trade', 'infrastructure'],
        },
    },

    # ── PORTUGAL / BASE.gov ────────────────────────────────────────────────
    {
        'name': 'BASE.gov.pt - Anúncios de Concursos',
        'organization': 'Base de Dados de Contratação Pública (Portugal)',
        'url': 'https://www.base.gov.pt/base4/pt/pesquisa/?tipo=anuncios',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.base.gov.pt/base4/pt/pesquisa/?tipo=anuncios',
            'api_url': 'https://www.base.gov.pt/base4/rest/anuncio',
            'item_selectors': [
                'table tbody tr',
                'div.item',
                'li.result',
                'article',
            ],
            'title_selector': 'a, td:nth-child(2)',
            'link_selector': 'a[href]',
            'description_selector': 'td, p',
            'deadline_selector': 'td:last-child, .prazo',
            'organization': 'Contratação Pública',
            'client': 'Entidade Pública',
            'country': 'Portugal',
            'language': 'pt',
        },
        'filters': {
            'countries': ['Portugal', 'PT'],
            'keywords': ['consultoria', 'consultor', 'estudos', 'assessoria', 'serviços técnicos', 'perito'],
            'sectors': ['consultoria', 'estudos', 'formação', 'TIC', 'ambiente', 'saúde'],
        },
    },
    {
        'name': 'UN Women - Procurement Notices',
        'organization': 'UN Women',
        'url': 'https://www.unwomen.org/en/about-us/procurement',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.unwomen.org/en/about-us/procurement',
            'item_selectors': [
                'article',
                'div.procurement-notice',
                'li',
                'tr',
            ],
            'title_selector': 'h2, h3, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.description',
            'deadline_selector': '.deadline, .date, time, td:last-child',
            'organization': 'UN Women',
            'client': 'UN Women',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['Africa', 'CPV'],
            'keywords': ['consultant', 'consultancy', 'expert', 'gender', 'evaluation', 'advisory'],
            'sectors': ['gender equality', 'women empowerment', 'civil society', 'governance'],
        },
    },

    # ── C1 / C2 EXPANSION ─────────────────────────────────────────────────────
    {
        'name': 'USAID - Partnership Opportunities',
        'organization': 'US Agency for International Development (USAID)',
        'url': 'https://www.usaid.gov/partnership-opportunities',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'USAIDScraper',
        'scraper_config': {
            'urls': [
                'https://www.usaid.gov/partnership-opportunities',
                'https://www.usaid.gov/west-africa-regional/business-opportunities',
                'https://www.usaid.gov/cabo-verde',
            ],
            'country': 'West Africa / International',
            'region': 'West Africa',
            'max_items': 100,
        },
        'filters': {
            'countries': ['CPV', 'West Africa', 'Africa'],
            'keywords': [
                'consultant', 'consultancy', 'RFP', 'solicitation',
                'request for proposals', 'technical assistance', 'advisory',
                'evaluation', 'assessment',
            ],
        },
    },
    {
        'name': 'FCDO - Find a Tender (UK Aid)',
        'organization': 'UK Foreign, Commonwealth & Development Office (FCDO)',
        'url': 'https://www.find-tender.service.gov.uk',
        'source_type': 'api',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'FCDOScraper',
        'scraper_config': {
            'buyer_id': 'GB-GOV-13',
            'days_back': 90,
            'max_items': 200,
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'International'],
            'keywords': [
                'consultant', 'consultancy', 'technical assistance', 'advisory',
                'evaluation', 'development', 'Africa', 'West Africa',
            ],
        },
    },
    {
        'name': 'DevelopmentAid - Tenders & Contracts',
        'organization': 'DevelopmentAid',
        'url': 'https://www.developmentaid.org/tenders/search',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.developmentaid.org/tenders/search',
            'item_selectors': [
                'div.tender-item',
                'article.tender',
                'div.result-item',
                'li.tender',
                'tr.tender-row',
                'div.card',
            ],
            'title_selector': 'h2, h3, h4, a.title, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.description, div.excerpt',
            'deadline_selector': '.deadline, .closing-date, time, span.date',
            'organization': 'DevelopmentAid',
            'client': 'Various Donors',
            'country': 'Africa / International',
            'language': 'en',
            'reject_title_patterns': [
                r'^(Sign up|Log in|Register|Subscribe)',
                r'\bpremium\b',
            ],
        },
        'filters': {
            'countries': ['CPV', 'Africa', 'West Africa'],
            'keywords': [
                'consultant', 'consultancy', 'technical assistance', 'advisory',
                'evaluation', 'development', 'project management',
            ],
        },
    },
    {
        'name': 'UNOPS - Procurement Notices',
        'organization': 'UNOPS',
        'url': 'https://www.unops.org/business/seek-work/consultancies',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.unops.org/business/seek-work/consultancies',
            'item_selectors': [
                'article',
                'div.vacancy-item',
                'div.result-card',
                'li.vacancy',
                'div.card',
                'tr',
            ],
            'title_selector': 'h2, h3, h4, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.description, div.body-text',
            'deadline_selector': '.deadline, .closing-date, time, td:last-child',
            'organization': 'UNOPS',
            'client': 'UNOPS / UN System',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': [
                'consultant', 'consultancy', 'individual contractor',
                'retainer', 'advisory', 'infrastructure', 'project management',
            ],
        },
    },
    {
        'name': 'UNDP - Procurement Notices (UNGM)',
        'organization': 'UNDP / UN System',
        'url': 'https://procurement-notices.undp.org',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'daily',
        'scraper_class': 'UNDPScraper',
        'scraper_config': {
            'api_url': 'https://www.ungm.org/Public/Notice',
            'rss_url': 'https://procurement-notices.undp.org/feed.cfm?po_filter=all',
            'notice_type': 0,
            'page_size': 50,
            'max_items': 200,
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': [
                'consultant', 'consultancy', 'individual contractor',
                'technical assistance', 'evaluation', 'assessment', 'advisory',
            ],
        },
    },
    {
        'name': 'UNICEF - Supply & Procurement Notices',
        'organization': 'UNICEF',
        'url': 'https://www.unicef.org/supply/procurement-notices',
        'source_type': 'portal',
        'status': 'active',
        'scrape_frequency': 'weekly',
        'scraper_class': 'GenericPortalScraper',
        'scraper_config': {
            'url': 'https://www.unicef.org/supply/procurement-notices',
            'item_selectors': [
                'article',
                'div.procurement-notice',
                'div.views-row',
                'li.views-row',
                'tr',
            ],
            'title_selector': 'h2, h3, h4, a',
            'link_selector': 'a[href]',
            'description_selector': 'p, div.field-body',
            'deadline_selector': '.date, time, td:last-child',
            'organization': 'UNICEF',
            'client': 'UNICEF',
            'country': 'Africa / International',
            'language': 'en',
        },
        'filters': {
            'countries': ['CPV', 'Africa'],
            'keywords': [
                'consultant', 'consultancy', 'individual contractor',
                'evaluation', 'assessment', 'technical assistance',
            ],
            'sectors': ['health', 'education', 'child protection', 'WASH', 'social policy'],
        },
    },

    # ══════════════════════════════════════════════════════════════════════════
    # COMPREHENSIVE EXPANSION — migration 0011
    # ══════════════════════════════════════════════════════════════════════════

    # ── New Multilaterals ─────────────────────────────────────────────────────
    {'name': 'IsDB - Procurement Notices', 'organization': 'Islamic Development Bank (IsDB)',
     'url': 'https://www.isdb.org/procurement', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.isdb.org/procurement',
                        'item_selectors': ['article', 'div.procurement-item', 'table tbody tr', 'li.node', 'div.card'],
                        'title_selector': 'h2, h3, h4, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.field-body',
                        'deadline_selector': '.deadline, .closing-date, time, td:last-child',
                        'organization': 'Islamic Development Bank', 'client': 'IsDB',
                        'country': 'Africa / International', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa', 'West Africa'],
                 'keywords': ['consultant', 'consultancy', 'advisory', 'technical assistance', 'expert', 'procurement']}},

    {'name': 'Global Fund - Procurement Notices', 'organization': 'The Global Fund',
     'url': 'https://www.theglobalfund.org/en/procurement/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.theglobalfund.org/en/procurement/',
                        'item_selectors': ['article', 'div.procurement-notice', 'li', 'tr', 'div.card'],
                        'title_selector': 'h2, h3, h4, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.description',
                        'deadline_selector': '.deadline, time, td:last-child',
                        'organization': 'The Global Fund', 'client': 'Global Fund',
                        'country': 'Africa', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['consultant', 'procurement', 'technical assistance', 'evaluation'],
                 'sectors': ['health', 'HIV/AIDS', 'tuberculosis', 'malaria']}},

    {'name': 'WFP - Procurement Notices', 'organization': 'World Food Programme (WFP)',
     'url': 'https://www.wfp.org/procurement', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.wfp.org/procurement',
                        'item_selectors': ['article', 'div.procurement-item', 'li', 'tr', 'div.card'],
                        'title_selector': 'h2, h3, h4, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.description',
                        'deadline_selector': '.deadline, time, td:last-child',
                        'organization': 'WFP', 'client': 'World Food Programme',
                        'country': 'Africa', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa', 'West Africa'],
                 'keywords': ['consultant', 'consultancy', 'technical assistance', 'food security']}},

    {'name': 'UNODC - Africa Grants for CSOs', 'organization': 'UNODC',
     'url': 'https://www.unodc.org/unodc/en/ngos/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.unodc.org/unodc/en/ngos/',
                        'item_selectors': ['div.content-item', 'article', 'li', 'div.node'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p', 'organization': 'UNODC',
                        'client': 'UNODC', 'country': 'Africa', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['grant', 'NGO', 'civil society', 'anti-corruption', 'governance']}},

    # ── New Bilateral ─────────────────────────────────────────────────────────
    {'name': 'GIZ - AU e-Tendering Portal', 'organization': 'GIZ / African Union',
     'url': 'https://au.giz.de/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://au.giz.de/',
                        'item_selectors': ['article', 'div.tender', 'tr', 'li.tender-item', 'div.card'],
                        'title_selector': 'h2, h3, h4, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.description',
                        'deadline_selector': '.deadline, time, td:last-child',
                        'organization': 'GIZ / African Union', 'client': 'GIZ AU Program',
                        'country': 'Africa', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa', 'West Africa'],
                 'keywords': ['consultant', 'tender', 'expert', 'advisory', 'technical assistance']}},

    {'name': 'Expertise France - Procurement & Tenders', 'organization': 'Expertise France',
     'url': 'https://www.expertisefrance.fr/en/public-procurement-and-tenders',
     'source_type': 'portal', 'status': 'active', 'scrape_frequency': 'weekly',
     'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.expertisefrance.fr/en/public-procurement-and-tenders',
                        'item_selectors': ['article', 'div.tender-item', 'li.appel-offre', 'div.card', 'tr'],
                        'title_selector': 'h2, h3, h4, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.description',
                        'deadline_selector': '.deadline, .date, time',
                        'organization': 'Expertise France', 'client': 'Expertise France / AFD Group',
                        'country': 'Africa / International', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa', 'PALOP', 'West Africa'],
                 'keywords': ['consultant', 'expert', 'advisory', 'technical assistance', 'evaluation']}},

    {'name': 'Irish Aid - Procurement Opportunities', 'organization': 'Irish Aid',
     'url': 'https://www.ireland.ie/en/irish-aid/about-us/procurement-opportunities/',
     'source_type': 'portal', 'status': 'active', 'scrape_frequency': 'weekly',
     'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.ireland.ie/en/irish-aid/about-us/procurement-opportunities/',
                        'item_selectors': ['article', 'div.tender-item', 'div.card', 'li', 'tr'],
                        'title_selector': 'h2, h3, h4, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.description',
                        'deadline_selector': '.deadline, time, td:last-child',
                        'organization': 'Irish Aid', 'client': 'Irish Aid',
                        'country': 'Africa / International', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa', 'West Africa'],
                 'keywords': ['consultant', 'consultancy', 'technical assistance', 'advisory', 'evaluation']}},

    {'name': 'AICS Italy - Global Tenders', 'organization': 'AICS Italy',
     'url': 'https://www.aics.gov.it/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.aics.gov.it/',
                        'item_selectors': ['article', 'div.tender-item', 'div.bando', 'li.bando', 'div.card'],
                        'title_selector': 'h2, h3, h4, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.field-body',
                        'deadline_selector': '.deadline, .scadenza, time',
                        'organization': 'AICS Italy', 'client': 'AICS',
                        'country': 'Africa', 'language': 'it'},
     'filters': {'countries': ['CPV', 'Africa', 'PALOP'],
                 'keywords': ['consulente', 'bando', 'gara', 'assistenza tecnica', 'consultant', 'tender']}},

    # ── Aggregators ───────────────────────────────────────────────────────────
    {'name': 'TenderSoko - East Africa Tenders', 'organization': 'TenderSoko',
     'url': 'https://www.tendersoko.com/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'daily', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.tendersoko.com/',
                        'item_selectors': ['article', 'div.tender-item', 'div.card', 'li.tender', 'tr'],
                        'title_selector': 'h2, h3, h4, a.tender-title, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.description',
                        'deadline_selector': '.deadline, .closing-date, time',
                        'organization': 'TenderSoko', 'client': 'Various',
                        'country': 'East Africa', 'language': 'en'},
     'filters': {'countries': ['KEN', 'TZA', 'UGA', 'ETH', 'RWA', 'Africa'],
                 'keywords': ['consultant', 'advisory', 'technical assistance', 'evaluation']}},

    {'name': 'FundsforNGOs - Grants Database', 'organization': 'FundsforNGOs',
     'url': 'https://www2.fundsforngos.org/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'daily', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www2.fundsforngos.org/',
                        'item_selectors': ['article', 'div.post', 'div.entry', 'li.post'],
                        'title_selector': 'h2, h3, a.entry-title, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.entry-summary',
                        'deadline_selector': '.deadline, time, .date',
                        'organization': 'FundsforNGOs', 'client': 'Various Donors',
                        'country': 'Africa / International', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['grant', 'funding', 'NGO', 'civil society', 'Africa']}},

    {'name': 'TerraViva Grants - Environment & Development', 'organization': 'TerraViva Grants',
     'url': 'https://www.terravivagrants.org/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.terravivagrants.org/',
                        'item_selectors': ['article', 'div.post', 'div.grant-item', 'li.post'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.excerpt',
                        'deadline_selector': '.deadline, time',
                        'organization': 'TerraViva Grants', 'client': 'Various Environmental Donors',
                        'country': 'Africa / International', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['grant', 'environment', 'climate', 'agriculture', 'development']}},

    {'name': 'AfricanNGOs - Funding Opportunities', 'organization': 'AfricanNGOs.org',
     'url': 'https://africanngos.org/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://africanngos.org/',
                        'item_selectors': ['article', 'div.post', 'div.opportunity', 'li.post'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.excerpt',
                        'organization': 'AfricanNGOs', 'client': 'Various',
                        'country': 'Africa', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['grant', 'NGO', 'funding', 'Africa', 'civil society']}},

    {'name': 'Africagateway - Consulting Tenders', 'organization': 'Africagateway',
     'url': 'https://www.africagateway.info/sector/Tenders-Consultancy',
     'source_type': 'portal', 'status': 'active', 'scrape_frequency': 'daily',
     'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.africagateway.info/sector/Tenders-Consultancy',
                        'item_selectors': ['article', 'div.tender-item', 'div.card', 'li', 'tr'],
                        'title_selector': 'h2, h3, a.title, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.description',
                        'deadline_selector': '.deadline, time',
                        'organization': 'Africagateway', 'client': 'Various',
                        'country': 'Africa', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa', 'West Africa'],
                 'keywords': ['consultant', 'advisory', 'tender', 'technical assistance']}},

    # ── National e-Procurement ─────────────────────────────────────────────────
    {'name': 'Cabo Verde - Contratação Pública', 'organization': 'Governo de Cabo Verde',
     'url': 'https://contratacao.publico.cv/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'daily', 'scraper_class': 'CaboVerdeProcurementScraper',
     'scraper_config': {'base_url': 'https://contratacao.publico.cv', 'max_items': 200, 'language': 'pt'},
     'filters': {'countries': ['CPV'],
                 'keywords': ['consultoria', 'consultor', 'serviços', 'concurso', 'ajuste direto']}},

    {'name': 'South Africa - eTenders Portal', 'organization': 'National Treasury South Africa',
     'url': 'https://etenders.treasury.gov.za/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'daily', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://etenders.treasury.gov.za/',
                        'item_selectors': ['table tbody tr', 'div.tender-item', 'article', 'li.tender'],
                        'title_selector': 'td:nth-child(2) a, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'td, p',
                        'deadline_selector': 'td:last-child, .closing-date',
                        'organization': 'South African Government', 'client': 'SA Government',
                        'country': 'South Africa', 'language': 'en'},
     'filters': {'countries': ['ZAF', 'South Africa'],
                 'keywords': ['consultant', 'advisory', 'evaluation', 'technical assistance']}},

    {'name': 'Kenya - PPIP Tenders', 'organization': 'PPIP Kenya',
     'url': 'https://ppip.go.ke/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'daily', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://ppip.go.ke/',
                        'item_selectors': ['table tbody tr', 'div.tender-item', 'article', 'li'],
                        'title_selector': 'td:nth-child(2) a, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'td, p', 'deadline_selector': 'td:last-child, .closing-date',
                        'organization': 'Kenya Government', 'client': 'Kenyan Public Entities',
                        'country': 'Kenya', 'language': 'en'},
     'filters': {'countries': ['KEN', 'Kenya'],
                 'keywords': ['consultant', 'advisory', 'evaluation']}},

    {'name': 'Nigeria - NOCOPO Federal Tenders', 'organization': 'NOCOPO Nigeria',
     'url': 'https://nocopo.gov.ng/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'daily', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://nocopo.gov.ng/',
                        'item_selectors': ['table tbody tr', 'div.tender', 'article', 'li.tender'],
                        'title_selector': 'td:nth-child(2) a, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'td, p', 'deadline_selector': 'td:last-child, .deadline',
                        'organization': 'Nigerian Government', 'client': 'Federal Ministries',
                        'country': 'Nigeria', 'language': 'en'},
     'filters': {'countries': ['NGA', 'Nigeria'],
                 'keywords': ['consultant', 'advisory', 'services']}},

    {'name': 'Ghana - GPPRA Tenders', 'organization': 'GPPRA Ghana',
     'url': 'https://ghanappra.gov.gh/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'daily', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://ghanappra.gov.gh/',
                        'item_selectors': ['table tbody tr', 'div.tender-item', 'article', 'li'],
                        'title_selector': 'td:nth-child(2) a, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'td, p', 'deadline_selector': 'td:last-child, .deadline',
                        'organization': 'Ghana Government', 'client': 'Ghanaian Public Entities',
                        'country': 'Ghana', 'language': 'en'},
     'filters': {'countries': ['GHA', 'Ghana'],
                 'keywords': ['consultant', 'advisory']}},

    {'name': 'Morocco - Marchés Publics', 'organization': 'Trésorerie Générale du Royaume',
     'url': 'http://www.marchespublics.gov.ma/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'http://www.marchespublics.gov.ma/',
                        'item_selectors': ['table tbody tr', 'div.marche-item', 'article', 'li'],
                        'title_selector': 'td:nth-child(2) a, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'td, p', 'deadline_selector': 'td:last-child, .date-limite',
                        'organization': 'Gouvernement du Maroc', 'client': 'Entités Publiques Marocaines',
                        'country': 'Morocco', 'language': 'fr'},
     'filters': {'countries': ['MAR', 'Morocco'],
                 'keywords': ['consultant', 'consultance', 'expertise', 'marché']},
     'verify_ssl': False},

    # ── Climate / Environment ─────────────────────────────────────────────────
    {'name': 'Green Climate Fund - Calls & Procurement', 'organization': 'Green Climate Fund (GCF)',
     'url': 'https://www.greenclimate.fund/calls', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.greenclimate.fund/calls',
                        'item_selectors': ['article', 'div.call-item', 'div.card', 'li', 'tr'],
                        'title_selector': 'h2, h3, h4, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.description',
                        'deadline_selector': '.deadline, time',
                        'organization': 'Green Climate Fund', 'client': 'GCF',
                        'country': 'Africa / International', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['grant', 'climate', 'adaptation', 'mitigation', 'call for proposals'],
                 'sectors': ['climate change', 'renewable energy', 'adaptation', 'resilience']}},

    {'name': 'Global Environment Facility - Calls', 'organization': 'GEF',
     'url': 'https://www.thegef.org/grants', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.thegef.org/grants',
                        'item_selectors': ['article', 'div.grant-item', 'div.card', 'li'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.description',
                        'organization': 'GEF', 'client': 'GEF',
                        'country': 'Africa / International', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['grant', 'environment', 'biodiversity', 'climate'],
                 'sectors': ['environment', 'biodiversity', 'climate', 'oceans']}},

    {'name': 'Green Climate Fund - Procurement', 'organization': 'Green Climate Fund (GCF)',
     'url': 'https://www.greenclimate.fund/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.greenclimate.fund/',
                        'item_selectors': ['article', 'div.procurement', 'div.card', 'li'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p',
                        'organization': 'GCF', 'client': 'GCF',
                        'country': 'Africa / International', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['consultant', 'procurement', 'technical assistance']}},

    {'name': 'NDC Partnership - Climate Grants', 'organization': 'NDC Partnership',
     'url': 'https://ndcpartnership.org/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://ndcpartnership.org/',
                        'item_selectors': ['article', 'div.opportunity', 'div.card', 'li'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p',
                        'organization': 'NDC Partnership', 'client': 'NDC Partnership',
                        'country': 'Africa', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['grant', 'climate', 'NDC', 'adaptation', 'resilience']}},

    {'name': 'African Water Facility - Grants', 'organization': 'African Water Facility',
     'url': 'https://www.africanwaterfacility.org/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.africanwaterfacility.org/',
                        'item_selectors': ['article', 'div.call-item', 'div.card', 'li'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p',
                        'organization': 'African Water Facility', 'client': 'AWF',
                        'country': 'Africa', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['grant', 'water', 'sanitation', 'WASH'],
                 'sectors': ['water', 'WASH', 'environment']}},

    # ── Foundations ───────────────────────────────────────────────────────────
    {'name': 'Mastercard Foundation - Grants', 'organization': 'Mastercard Foundation',
     'url': 'https://mastercardfdn.org/all-initiatives/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://mastercardfdn.org/all-initiatives/',
                        'item_selectors': ['article', 'div.initiative-item', 'div.card', 'li'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.excerpt',
                        'organization': 'Mastercard Foundation', 'client': 'Mastercard Foundation',
                        'country': 'Africa', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa', 'West Africa'],
                 'keywords': ['grant', 'youth', 'education', 'economic inclusion', 'Africa']}},

    {'name': 'Ford Foundation - Grants', 'organization': 'Ford Foundation',
     'url': 'https://www.fordfoundation.org/work/our-grants/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.fordfoundation.org/work/our-grants/',
                        'item_selectors': ['article', 'div.grant-item', 'div.card', 'li'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.excerpt',
                        'organization': 'Ford Foundation', 'client': 'Ford Foundation',
                        'country': 'Africa / International', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['grant', 'social justice', 'inequality', 'democracy', 'civil society']}},

    {'name': 'Bill & Melinda Gates Foundation - Grants', 'organization': 'Gates Foundation',
     'url': 'https://www.gatesfoundation.org/about/how-we-work/quick-links/grants-lookup',
     'source_type': 'portal', 'status': 'active', 'scrape_frequency': 'weekly',
     'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://www.gatesfoundation.org/about/how-we-work/quick-links/grants-lookup',
                        'item_selectors': ['article', 'div.grant-item', 'div.card', 'li', 'tr'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.description',
                        'organization': 'Gates Foundation', 'client': 'Gates Foundation',
                        'country': 'Africa / International', 'language': 'en'},
     'filters': {'countries': ['CPV', 'Africa'],
                 'keywords': ['grant', 'health', 'agriculture', 'development', 'Africa']}},

    {'name': 'AULP - Universidades Portuguesas', 'organization': 'AULP',
     'url': 'https://aulp.org/', 'source_type': 'portal', 'status': 'active',
     'scrape_frequency': 'weekly', 'scraper_class': 'GenericPortalScraper',
     'scraper_config': {'url': 'https://aulp.org/',
                        'item_selectors': ['article', 'div.post', 'div.news-item', 'li.post'],
                        'title_selector': 'h2, h3, a', 'link_selector': 'a[href]',
                        'description_selector': 'p, div.excerpt',
                        'organization': 'AULP', 'client': 'AULP',
                        'country': 'PALOP / Portugal', 'language': 'pt'},
     'filters': {'countries': ['CPV', 'PT', 'AO', 'MZ', 'GW'],
                 'keywords': ['bolsa', 'financiamento', 'mobilidade', 'formação', 'edital']}},
]


class Command(BaseCommand):
    help = 'Initialize scraping sources for Cabo Verde and Africa consultancy opportunities'

    def add_arguments(self, parser):
        parser.add_argument(
            '--reset',
            action='store_true',
            help='Reset existing sources (delete and recreate)',
        )

    def handle(self, *args, **options):
        reset = options['reset']

        if reset:
            count = ScrapingSource.objects.all().count()
            ScrapingSource.objects.all().delete()
            self.stdout.write(self.style.WARNING(f'Deleted {count} existing sources'))

        created_count = 0
        updated_count = 0

        for src_data in DEFAULT_SOURCES:
            source_status = src_data['status']
            if src_data['scraper_class'] in ('EUFundingScraper', 'GIZScraper'):
                source_status = 'active'

            source, created = ScrapingSource.objects.update_or_create(
                name=src_data['name'],
                defaults={
                    'organization': src_data['organization'],
                    'url': src_data['url'],
                    'source_type': src_data['source_type'],
                    'status': source_status,
                    'scrape_frequency': src_data['scrape_frequency'],
                    'scraper_class': src_data['scraper_class'],
                    'scraper_config': src_data.get('scraper_config', {}),
                    'filters': src_data.get('filters', {}),
                }
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created: {source.name}'))
            else:
                updated_count += 1
                self.stdout.write(self.style.NOTICE(f'Updated: {source.name}'))

        self.stdout.write(
            f'Done: {created_count} created, {updated_count} updated.'
        )
